package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcsAcessoUsuarios generated by hbm2java
 */
@Entity
@Table(name="acs_acesso_usuarios"
    ,catalog="jvmdsoftware"
)
public class AcsAcessoUsuarios  implements java.io.Serializable {


     private Integer idAcesso;
     private PubUsuario pubUsuario;
     private Date dataHoraLogin;
     private Date dataHoraLogoff;

    public AcsAcessoUsuarios() {
    }

	
    public AcsAcessoUsuarios(PubUsuario pubUsuario, Date dataHoraLogin) {
        this.pubUsuario = pubUsuario;
        this.dataHoraLogin = dataHoraLogin;
    }
    public AcsAcessoUsuarios(PubUsuario pubUsuario, Date dataHoraLogin, Date dataHoraLogoff) {
       this.pubUsuario = pubUsuario;
       this.dataHoraLogin = dataHoraLogin;
       this.dataHoraLogoff = dataHoraLogoff;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_acesso", unique=true, nullable=false)
    public Integer getIdAcesso() {
        return this.idAcesso;
    }
    
    public void setIdAcesso(Integer idAcesso) {
        this.idAcesso = idAcesso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario", nullable=false)
    public PubUsuario getPubUsuario() {
        return this.pubUsuario;
    }
    
    public void setPubUsuario(PubUsuario pubUsuario) {
        this.pubUsuario = pubUsuario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_hora_login", nullable=false, length=19)
    public Date getDataHoraLogin() {
        return this.dataHoraLogin;
    }
    
    public void setDataHoraLogin(Date dataHoraLogin) {
        this.dataHoraLogin = dataHoraLogin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_hora_logoff", length=19)
    public Date getDataHoraLogoff() {
        return this.dataHoraLogoff;
    }
    
    public void setDataHoraLogoff(Date dataHoraLogoff) {
        this.dataHoraLogoff = dataHoraLogoff;
    }




}


