package br.com.jvmsoftware.entities;
// Generated 9/Abr/2016 18:34:16 by Hibernate Tools 4.3.1



/**
 * AcsEmpresaFuncionalidade generated by hbm2java
 */
public class AcsEmpresaFuncionalidade  implements java.io.Serializable {


     private Integer id;
     private PubEmpresa pubEmpresa;
     private PubFuncionalidade pubFuncionalidade;
     private boolean desabilitado;

    public AcsEmpresaFuncionalidade() {
    }

    public AcsEmpresaFuncionalidade(PubEmpresa pubEmpresa, PubFuncionalidade pubFuncionalidade, boolean desabilitado) {
       this.pubEmpresa = pubEmpresa;
       this.pubFuncionalidade = pubFuncionalidade;
       this.desabilitado = desabilitado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }
    public PubFuncionalidade getPubFuncionalidade() {
        return this.pubFuncionalidade;
    }
    
    public void setPubFuncionalidade(PubFuncionalidade pubFuncionalidade) {
        this.pubFuncionalidade = pubFuncionalidade;
    }
    public boolean getDesabilitado() {
        return this.desabilitado;
    }
    
    public void setDesabilitado(boolean desabilitado) {
        this.desabilitado = desabilitado;
    }




}


