package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcsEmpresaSistema generated by hbm2java
 */
@Entity
@Table(name="acs_empresa_sistema"
    ,catalog="jvmdsoftware"
)
public class AcsEmpresaSistema  implements java.io.Serializable {


     private Integer idEmpresaSistema;
     private PubEmpresa pubEmpresa;
     private PubSistema pubSistema;
     private boolean ativo;

    public AcsEmpresaSistema() {
    }

    public AcsEmpresaSistema(PubEmpresa pubEmpresa, PubSistema pubSistema, boolean ativo) {
       this.pubEmpresa = pubEmpresa;
       this.pubSistema = pubSistema;
       this.ativo = ativo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_empresa_sistema", unique=true, nullable=false)
    public Integer getIdEmpresaSistema() {
        return this.idEmpresaSistema;
    }
    
    public void setIdEmpresaSistema(Integer idEmpresaSistema) {
        this.idEmpresaSistema = idEmpresaSistema;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa", nullable=false)
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sistema", nullable=false)
    public PubSistema getPubSistema() {
        return this.pubSistema;
    }
    
    public void setPubSistema(PubSistema pubSistema) {
        this.pubSistema = pubSistema;
    }

    
    @Column(name="ativo", nullable=false)
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }




}


