package br.com.jvmsoftware.entities;
// Generated 11/Abr/2016 15:26:22 by Hibernate Tools 4.3.1



/**
 * AcsUsuarioFuncionalidade generated by hbm2java
 */
public class AcsUsuarioFuncionalidade  implements java.io.Serializable {


     private Integer id;
     private PubEmpresa pubEmpresa;
     private PubFuncionalidade pubFuncionalidade;
     private PubUsuario pubUsuario;
     private boolean view;
     private boolean add;
     private boolean edit;
     private boolean delete;
     private boolean process;

    public AcsUsuarioFuncionalidade() {
    }

    public AcsUsuarioFuncionalidade(PubEmpresa pubEmpresa, PubFuncionalidade pubFuncionalidade, PubUsuario pubUsuario, boolean view, boolean add, boolean edit, boolean delete, boolean process) {
       this.pubEmpresa = pubEmpresa;
       this.pubFuncionalidade = pubFuncionalidade;
       this.pubUsuario = pubUsuario;
       this.view = view;
       this.add = add;
       this.edit = edit;
       this.delete = delete;
       this.process = process;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }
    public PubFuncionalidade getPubFuncionalidade() {
        return this.pubFuncionalidade;
    }
    
    public void setPubFuncionalidade(PubFuncionalidade pubFuncionalidade) {
        this.pubFuncionalidade = pubFuncionalidade;
    }
    public PubUsuario getPubUsuario() {
        return this.pubUsuario;
    }
    
    public void setPubUsuario(PubUsuario pubUsuario) {
        this.pubUsuario = pubUsuario;
    }
    public boolean getView() {
        return this.view;
    }
    
    public void setView(boolean view) {
        this.view = view;
    }
    public boolean isAdd() {
        return this.add;
    }
    
    public void setAdd(boolean add) {
        this.add = add;
    }
    public boolean isEdit() {
        return this.edit;
    }
    
    public void setEdit(boolean edit) {
        this.edit = edit;
    }
    public boolean isDelete() {
        return this.delete;
    }
    
    public void setDelete(boolean delete) {
        this.delete = delete;
    }
    public boolean isProcess() {
        return this.process;
    }
    
    public void setProcess(boolean process) {
        this.process = process;
    }




}


