package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AcsUsuarioSistema generated by hbm2java
 */
@Entity
@Table(name="acs_usuario_sistema"
    ,catalog="jvmdsoftware"
)
public class AcsUsuarioSistema  implements java.io.Serializable {


     private Integer idUsuarioSistema;
     private PubEmpresa pubEmpresa;
     private PubSistema pubSistema;
     private PubUsuario pubUsuario;
     private boolean ativo;

    public AcsUsuarioSistema() {
    }

    public AcsUsuarioSistema(PubEmpresa pubEmpresa, PubSistema pubSistema, PubUsuario pubUsuario, boolean ativo) {
       this.pubEmpresa = pubEmpresa;
       this.pubSistema = pubSistema;
       this.pubUsuario = pubUsuario;
       this.ativo = ativo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_usuario_sistema", unique=true, nullable=false)
    public Integer getIdUsuarioSistema() {
        return this.idUsuarioSistema;
    }
    
    public void setIdUsuarioSistema(Integer idUsuarioSistema) {
        this.idUsuarioSistema = idUsuarioSistema;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa", nullable=false)
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sistema", nullable=false)
    public PubSistema getPubSistema() {
        return this.pubSistema;
    }
    
    public void setPubSistema(PubSistema pubSistema) {
        this.pubSistema = pubSistema;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario", nullable=false)
    public PubUsuario getPubUsuario() {
        return this.pubUsuario;
    }
    
    public void setPubUsuario(PubUsuario pubUsuario) {
        this.pubUsuario = pubUsuario;
    }

    
    @Column(name="ativo", nullable=false)
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }




}


