package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CadEnderecos generated by hbm2java
 */
@Entity
@Table(name="cad_enderecos"
    ,catalog="jvmdsoftware"
)
public class CadEnderecos  implements java.io.Serializable {


     private Integer idEndereco;
     private CadPessoa cadPessoa;
     private PubEstado pubEstado;
     private PubMunicipio pubMunicipio;
     private PubTipoEndereco pubTipoEndereco;
     private String endereco;
     private Integer numero;
     private String bairro;
     private String cep;
     private String complemento;
     private Set cadPessoas = new HashSet(0);

    public CadEnderecos() {
    }

	
    public CadEnderecos(CadPessoa cadPessoa, PubTipoEndereco pubTipoEndereco) {
        this.cadPessoa = cadPessoa;
        this.pubTipoEndereco = pubTipoEndereco;
    }
    public CadEnderecos(CadPessoa cadPessoa, PubEstado pubEstado, PubMunicipio pubMunicipio, PubTipoEndereco pubTipoEndereco, String endereco, Integer numero, String bairro, String cep, String complemento, Set cadPessoas) {
       this.cadPessoa = cadPessoa;
       this.pubEstado = pubEstado;
       this.pubMunicipio = pubMunicipio;
       this.pubTipoEndereco = pubTipoEndereco;
       this.endereco = endereco;
       this.numero = numero;
       this.bairro = bairro;
       this.cep = cep;
       this.complemento = complemento;
       this.cadPessoas = cadPessoas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_endereco", unique=true, nullable=false)
    public Integer getIdEndereco() {
        return this.idEndereco;
    }
    
    public void setIdEndereco(Integer idEndereco) {
        this.idEndereco = idEndereco;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pessoa", nullable=false)
    public CadPessoa getCadPessoa() {
        return this.cadPessoa;
    }
    
    public void setCadPessoa(CadPessoa cadPessoa) {
        this.cadPessoa = cadPessoa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="estado")
    public PubEstado getPubEstado() {
        return this.pubEstado;
    }
    
    public void setPubEstado(PubEstado pubEstado) {
        this.pubEstado = pubEstado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="municipio")
    public PubMunicipio getPubMunicipio() {
        return this.pubMunicipio;
    }
    
    public void setPubMunicipio(PubMunicipio pubMunicipio) {
        this.pubMunicipio = pubMunicipio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_endereco", nullable=false)
    public PubTipoEndereco getPubTipoEndereco() {
        return this.pubTipoEndereco;
    }
    
    public void setPubTipoEndereco(PubTipoEndereco pubTipoEndereco) {
        this.pubTipoEndereco = pubTipoEndereco;
    }

    
    @Column(name="endereco", length=100)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="numero")
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    
    @Column(name="bairro", length=50)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="cep", length=8)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="complemento", length=100)
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cadEnderecos")
    public Set getCadPessoas() {
        return this.cadPessoas;
    }
    
    public void setCadPessoas(Set cadPessoas) {
        this.cadPessoas = cadPessoas;
    }




}


