package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CadEquipamentos generated by hbm2java
 */
@Entity
@Table(name="cad_equipamentos"
    ,catalog="jvmdsoftware"
)
public class CadEquipamentos  implements java.io.Serializable {


     private Integer idEquipamento;
     private CadPessoa cadPessoa;
     private PubEmpresa pubEmpresa;
     private PubTipoEquipamento pubTipoEquipamento;
     private String equipamento;
     private String observacao;
     private Set servOrdemServicos = new HashSet(0);

    public CadEquipamentos() {
    }

	
    public CadEquipamentos(CadPessoa cadPessoa, PubEmpresa pubEmpresa, PubTipoEquipamento pubTipoEquipamento, String equipamento) {
        this.cadPessoa = cadPessoa;
        this.pubEmpresa = pubEmpresa;
        this.pubTipoEquipamento = pubTipoEquipamento;
        this.equipamento = equipamento;
    }
    public CadEquipamentos(CadPessoa cadPessoa, PubEmpresa pubEmpresa, PubTipoEquipamento pubTipoEquipamento, String equipamento, String observacao, Set servOrdemServicos) {
       this.cadPessoa = cadPessoa;
       this.pubEmpresa = pubEmpresa;
       this.pubTipoEquipamento = pubTipoEquipamento;
       this.equipamento = equipamento;
       this.observacao = observacao;
       this.servOrdemServicos = servOrdemServicos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_equipamento", unique=true, nullable=false)
    public Integer getIdEquipamento() {
        return this.idEquipamento;
    }
    
    public void setIdEquipamento(Integer idEquipamento) {
        this.idEquipamento = idEquipamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pessoa", nullable=false)
    public CadPessoa getCadPessoa() {
        return this.cadPessoa;
    }
    
    public void setCadPessoa(CadPessoa cadPessoa) {
        this.cadPessoa = cadPessoa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa", nullable=false)
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_equipamento", nullable=false)
    public PubTipoEquipamento getPubTipoEquipamento() {
        return this.pubTipoEquipamento;
    }
    
    public void setPubTipoEquipamento(PubTipoEquipamento pubTipoEquipamento) {
        this.pubTipoEquipamento = pubTipoEquipamento;
    }

    
    @Column(name="equipamento", nullable=false, length=50)
    public String getEquipamento() {
        return this.equipamento;
    }
    
    public void setEquipamento(String equipamento) {
        this.equipamento = equipamento;
    }

    
    @Column(name="observacao")
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cadEquipamentos")
    public Set getServOrdemServicos() {
        return this.servOrdemServicos;
    }
    
    public void setServOrdemServicos(Set servOrdemServicos) {
        this.servOrdemServicos = servOrdemServicos;
    }




}


