package br.com.jvmsoftware.entities;
// Generated 9/Abr/2016 18:34:16 by Hibernate Tools 4.3.1



/**
 * CadImoveis generated by hbm2java
 */
public class CadImoveis  implements java.io.Serializable {


     private Integer idImovel;
     private CadPessoa cadPessoa;
     private PubEmpresa pubEmpresa;
     private PubTipoImovel pubTipoImovel;
     private String imovel;
     private String observacao;

    public CadImoveis() {
    }

	
    public CadImoveis(CadPessoa cadPessoa, PubEmpresa pubEmpresa, PubTipoImovel pubTipoImovel, String imovel) {
        this.cadPessoa = cadPessoa;
        this.pubEmpresa = pubEmpresa;
        this.pubTipoImovel = pubTipoImovel;
        this.imovel = imovel;
    }
    public CadImoveis(CadPessoa cadPessoa, PubEmpresa pubEmpresa, PubTipoImovel pubTipoImovel, String imovel, String observacao) {
       this.cadPessoa = cadPessoa;
       this.pubEmpresa = pubEmpresa;
       this.pubTipoImovel = pubTipoImovel;
       this.imovel = imovel;
       this.observacao = observacao;
    }
   
    public Integer getIdImovel() {
        return this.idImovel;
    }
    
    public void setIdImovel(Integer idImovel) {
        this.idImovel = idImovel;
    }
    public CadPessoa getCadPessoa() {
        return this.cadPessoa;
    }
    
    public void setCadPessoa(CadPessoa cadPessoa) {
        this.cadPessoa = cadPessoa;
    }
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }
    public PubTipoImovel getPubTipoImovel() {
        return this.pubTipoImovel;
    }
    
    public void setPubTipoImovel(PubTipoImovel pubTipoImovel) {
        this.pubTipoImovel = pubTipoImovel;
    }
    public String getImovel() {
        return this.imovel;
    }
    
    public void setImovel(String imovel) {
        this.imovel = imovel;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }




}


