package br.com.jvmsoftware.entities;
// Generated 17/Abr/2016 23:30:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CadImoveis generated by hbm2java
 */
public class CadImoveis  implements java.io.Serializable {


     private Integer idImovel;
     private CadPessoa cadPessoa;
     private PubEmpresa pubEmpresa;
     private PubTipoImovel pubTipoImovel;
     private String imovel;
     private String observacao;
     private Set<ServOrdemServico> servOrdemServicos = new HashSet<ServOrdemServico>(0);

    public CadImoveis() {
    }

	
    public CadImoveis(CadPessoa cadPessoa, PubEmpresa pubEmpresa, PubTipoImovel pubTipoImovel, String imovel) {
        this.cadPessoa = cadPessoa;
        this.pubEmpresa = pubEmpresa;
        this.pubTipoImovel = pubTipoImovel;
        this.imovel = imovel;
    }
    public CadImoveis(CadPessoa cadPessoa, PubEmpresa pubEmpresa, PubTipoImovel pubTipoImovel, String imovel, String observacao, Set<ServOrdemServico> servOrdemServicos) {
       this.cadPessoa = cadPessoa;
       this.pubEmpresa = pubEmpresa;
       this.pubTipoImovel = pubTipoImovel;
       this.imovel = imovel;
       this.observacao = observacao;
       this.servOrdemServicos = servOrdemServicos;
    }
   
    public Integer getIdImovel() {
        return this.idImovel;
    }
    
    public void setIdImovel(Integer idImovel) {
        this.idImovel = idImovel;
    }
    public CadPessoa getCadPessoa() {
        return this.cadPessoa;
    }
    
    public void setCadPessoa(CadPessoa cadPessoa) {
        this.cadPessoa = cadPessoa;
    }
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }
    public PubTipoImovel getPubTipoImovel() {
        return this.pubTipoImovel;
    }
    
    public void setPubTipoImovel(PubTipoImovel pubTipoImovel) {
        this.pubTipoImovel = pubTipoImovel;
    }
    public String getImovel() {
        return this.imovel;
    }
    
    public void setImovel(String imovel) {
        this.imovel = imovel;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Set<ServOrdemServico> getServOrdemServicos() {
        return this.servOrdemServicos;
    }
    
    public void setServOrdemServicos(Set<ServOrdemServico> servOrdemServicos) {
        this.servOrdemServicos = servOrdemServicos;
    }




}


