package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CadImoveis generated by hbm2java
 */
@Entity
@Table(name="cad_imoveis"
    ,catalog="jvmdsoftware"
)
public class CadImoveis  implements java.io.Serializable {


     private Integer idImovel;
     private CadPessoa cadPessoa;
     private PubEmpresa pubEmpresa;
     private PubTipoImovel pubTipoImovel;
     private String imovel;
     private String observacao;
     private Set servOrdemServicos = new HashSet(0);

    public CadImoveis() {
    }

	
    public CadImoveis(CadPessoa cadPessoa, PubEmpresa pubEmpresa, PubTipoImovel pubTipoImovel, String imovel) {
        this.cadPessoa = cadPessoa;
        this.pubEmpresa = pubEmpresa;
        this.pubTipoImovel = pubTipoImovel;
        this.imovel = imovel;
    }
    public CadImoveis(CadPessoa cadPessoa, PubEmpresa pubEmpresa, PubTipoImovel pubTipoImovel, String imovel, String observacao, Set servOrdemServicos) {
       this.cadPessoa = cadPessoa;
       this.pubEmpresa = pubEmpresa;
       this.pubTipoImovel = pubTipoImovel;
       this.imovel = imovel;
       this.observacao = observacao;
       this.servOrdemServicos = servOrdemServicos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_imovel", unique=true, nullable=false)
    public Integer getIdImovel() {
        return this.idImovel;
    }
    
    public void setIdImovel(Integer idImovel) {
        this.idImovel = idImovel;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pessoa", nullable=false)
    public CadPessoa getCadPessoa() {
        return this.cadPessoa;
    }
    
    public void setCadPessoa(CadPessoa cadPessoa) {
        this.cadPessoa = cadPessoa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa", nullable=false)
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_imovel", nullable=false)
    public PubTipoImovel getPubTipoImovel() {
        return this.pubTipoImovel;
    }
    
    public void setPubTipoImovel(PubTipoImovel pubTipoImovel) {
        this.pubTipoImovel = pubTipoImovel;
    }

    
    @Column(name="imovel", nullable=false, length=50)
    public String getImovel() {
        return this.imovel;
    }
    
    public void setImovel(String imovel) {
        this.imovel = imovel;
    }

    
    @Column(name="observacao")
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cadImoveis")
    public Set getServOrdemServicos() {
        return this.servOrdemServicos;
    }
    
    public void setServOrdemServicos(Set servOrdemServicos) {
        this.servOrdemServicos = servOrdemServicos;
    }




}


