package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CadProduto generated by hbm2java
 */
@Entity
@Table(name="cad_produto"
    ,catalog="jvmdsoftware"
)
public class CadProduto  implements java.io.Serializable {


     private Integer idProduto;
     private PubEmbalagem pubEmbalagem;
     private PubEmpresa pubEmpresa;
     private String produto;
     private String descricao;
     private BigDecimal preco;
     private Integer qtdeEmbalagem;
     private boolean ativo;
     private Set comRelVendaProdutos = new HashSet(0);
     private Set comRelCompraOrdemProdutos = new HashSet(0);
     private Set cadRelProdFornecs = new HashSet(0);

    public CadProduto() {
    }

	
    public CadProduto(PubEmpresa pubEmpresa, String produto, boolean ativo) {
        this.pubEmpresa = pubEmpresa;
        this.produto = produto;
        this.ativo = ativo;
    }
    public CadProduto(PubEmbalagem pubEmbalagem, PubEmpresa pubEmpresa, String produto, String descricao, BigDecimal preco, Integer qtdeEmbalagem, boolean ativo, Set comRelVendaProdutos, Set comRelCompraOrdemProdutos, Set cadRelProdFornecs) {
       this.pubEmbalagem = pubEmbalagem;
       this.pubEmpresa = pubEmpresa;
       this.produto = produto;
       this.descricao = descricao;
       this.preco = preco;
       this.qtdeEmbalagem = qtdeEmbalagem;
       this.ativo = ativo;
       this.comRelVendaProdutos = comRelVendaProdutos;
       this.comRelCompraOrdemProdutos = comRelCompraOrdemProdutos;
       this.cadRelProdFornecs = cadRelProdFornecs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_produto", unique=true, nullable=false)
    public Integer getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Integer idProduto) {
        this.idProduto = idProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="embalagem")
    public PubEmbalagem getPubEmbalagem() {
        return this.pubEmbalagem;
    }
    
    public void setPubEmbalagem(PubEmbalagem pubEmbalagem) {
        this.pubEmbalagem = pubEmbalagem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa", nullable=false)
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }

    
    @Column(name="produto", nullable=false, length=50)
    public String getProduto() {
        return this.produto;
    }
    
    public void setProduto(String produto) {
        this.produto = produto;
    }

    
    @Column(name="descricao")
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="preco", precision=10)
    public BigDecimal getPreco() {
        return this.preco;
    }
    
    public void setPreco(BigDecimal preco) {
        this.preco = preco;
    }

    
    @Column(name="qtde_embalagem")
    public Integer getQtdeEmbalagem() {
        return this.qtdeEmbalagem;
    }
    
    public void setQtdeEmbalagem(Integer qtdeEmbalagem) {
        this.qtdeEmbalagem = qtdeEmbalagem;
    }

    
    @Column(name="ativo", nullable=false)
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cadProduto")
    public Set getComRelVendaProdutos() {
        return this.comRelVendaProdutos;
    }
    
    public void setComRelVendaProdutos(Set comRelVendaProdutos) {
        this.comRelVendaProdutos = comRelVendaProdutos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cadProduto")
    public Set getComRelCompraOrdemProdutos() {
        return this.comRelCompraOrdemProdutos;
    }
    
    public void setComRelCompraOrdemProdutos(Set comRelCompraOrdemProdutos) {
        this.comRelCompraOrdemProdutos = comRelCompraOrdemProdutos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cadProduto")
    public Set getCadRelProdFornecs() {
        return this.cadRelProdFornecs;
    }
    
    public void setCadRelProdFornecs(Set cadRelProdFornecs) {
        this.cadRelProdFornecs = cadRelProdFornecs;
    }




}


