package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CadPessoa generated by hbm2java
 */
@Entity
@Table(name="cad_pessoa"
    ,catalog="jvmdsoftware"
)
public class CadPessoa  implements java.io.Serializable {


     private Integer idPessoa;
     private CadEnderecos cadEnderecos;
     private PubEmpresa pubEmpresa;
     private PubTipoCadastro pubTipoCadastro;
     private Date dataCadastro;
     private String cpfCnpj;
     private String nomeRazaoSocial;
     private String apelidoFantasia;
     private String emailResponsavel;
     private String telefone;
     private String telefone1;
     private boolean cliente;
     private boolean fornecedor;
     private boolean funcionario;
     private boolean transportador;
     private Set cadEquipamentoses = new HashSet(0);
     private Set cadImoveises = new HashSet(0);
     private Set servItemOrdemServicos = new HashSet(0);
     private Set cadVeiculoses = new HashSet(0);
     private Set cadEnderecoses = new HashSet(0);
     private Set cadRelServFornecs = new HashSet(0);
     private Set servOrdemServicos = new HashSet(0);
     private Set cadRelProdFornecs = new HashSet(0);

    public CadPessoa() {
    }

	
    public CadPessoa(PubEmpresa pubEmpresa, PubTipoCadastro pubTipoCadastro, String nomeRazaoSocial, String apelidoFantasia, boolean cliente, boolean fornecedor, boolean funcionario, boolean transportador) {
        this.pubEmpresa = pubEmpresa;
        this.pubTipoCadastro = pubTipoCadastro;
        this.nomeRazaoSocial = nomeRazaoSocial;
        this.apelidoFantasia = apelidoFantasia;
        this.cliente = cliente;
        this.fornecedor = fornecedor;
        this.funcionario = funcionario;
        this.transportador = transportador;
    }
    public CadPessoa(CadEnderecos cadEnderecos, PubEmpresa pubEmpresa, PubTipoCadastro pubTipoCadastro, Date dataCadastro, String cpfCnpj, String nomeRazaoSocial, String apelidoFantasia, String emailResponsavel, String telefone, String telefone1, boolean cliente, boolean fornecedor, boolean funcionario, boolean transportador, Set cadEquipamentoses, Set cadImoveises, Set servItemOrdemServicos, Set cadVeiculoses, Set cadEnderecoses, Set cadRelServFornecs, Set servOrdemServicos, Set cadRelProdFornecs) {
       this.cadEnderecos = cadEnderecos;
       this.pubEmpresa = pubEmpresa;
       this.pubTipoCadastro = pubTipoCadastro;
       this.dataCadastro = dataCadastro;
       this.cpfCnpj = cpfCnpj;
       this.nomeRazaoSocial = nomeRazaoSocial;
       this.apelidoFantasia = apelidoFantasia;
       this.emailResponsavel = emailResponsavel;
       this.telefone = telefone;
       this.telefone1 = telefone1;
       this.cliente = cliente;
       this.fornecedor = fornecedor;
       this.funcionario = funcionario;
       this.transportador = transportador;
       this.cadEquipamentoses = cadEquipamentoses;
       this.cadImoveises = cadImoveises;
       this.servItemOrdemServicos = servItemOrdemServicos;
       this.cadVeiculoses = cadVeiculoses;
       this.cadEnderecoses = cadEnderecoses;
       this.cadRelServFornecs = cadRelServFornecs;
       this.servOrdemServicos = servOrdemServicos;
       this.cadRelProdFornecs = cadRelProdFornecs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_pessoa", unique=true, nullable=false)
    public Integer getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(Integer idPessoa) {
        this.idPessoa = idPessoa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="endereco_padrao")
    public CadEnderecos getCadEnderecos() {
        return this.cadEnderecos;
    }
    
    public void setCadEnderecos(CadEnderecos cadEnderecos) {
        this.cadEnderecos = cadEnderecos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa", nullable=false)
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_cadastro", nullable=false)
    public PubTipoCadastro getPubTipoCadastro() {
        return this.pubTipoCadastro;
    }
    
    public void setPubTipoCadastro(PubTipoCadastro pubTipoCadastro) {
        this.pubTipoCadastro = pubTipoCadastro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_cadastro", length=10)
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }

    
    @Column(name="cpf_cnpj", length=15)
    public String getCpfCnpj() {
        return this.cpfCnpj;
    }
    
    public void setCpfCnpj(String cpfCnpj) {
        this.cpfCnpj = cpfCnpj;
    }

    
    @Column(name="nome_razao_social", nullable=false, length=150)
    public String getNomeRazaoSocial() {
        return this.nomeRazaoSocial;
    }
    
    public void setNomeRazaoSocial(String nomeRazaoSocial) {
        this.nomeRazaoSocial = nomeRazaoSocial;
    }

    
    @Column(name="apelido_fantasia", nullable=false, length=60)
    public String getApelidoFantasia() {
        return this.apelidoFantasia;
    }
    
    public void setApelidoFantasia(String apelidoFantasia) {
        this.apelidoFantasia = apelidoFantasia;
    }

    
    @Column(name="email_responsavel", length=50)
    public String getEmailResponsavel() {
        return this.emailResponsavel;
    }
    
    public void setEmailResponsavel(String emailResponsavel) {
        this.emailResponsavel = emailResponsavel;
    }

    
    @Column(name="telefone", length=11)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="telefone1", length=11)
    public String getTelefone1() {
        return this.telefone1;
    }
    
    public void setTelefone1(String telefone1) {
        this.telefone1 = telefone1;
    }

    
    @Column(name="cliente", nullable=false)
    public boolean getCliente() {
        return this.cliente;
    }
    
    public void setCliente(boolean cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="fornecedor", nullable=false)
    public boolean isFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(boolean fornecedor) {
        this.fornecedor = fornecedor;
    }

    
    @Column(name="funcionario", nullable=false)
    public boolean isFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(boolean funcionario) {
        this.funcionario = funcionario;
    }

    
    @Column(name="transportador", nullable=false)
    public boolean getTransportador() {
        return this.transportador;
    }
    
    public void setTransportador(boolean transportador) {
        this.transportador = transportador;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cadPessoa")
    public Set getCadEquipamentoses() {
        return this.cadEquipamentoses;
    }
    
    public void setCadEquipamentoses(Set cadEquipamentoses) {
        this.cadEquipamentoses = cadEquipamentoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cadPessoa")
    public Set getCadImoveises() {
        return this.cadImoveises;
    }
    
    public void setCadImoveises(Set cadImoveises) {
        this.cadImoveises = cadImoveises;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cadPessoa")
    public Set getServItemOrdemServicos() {
        return this.servItemOrdemServicos;
    }
    
    public void setServItemOrdemServicos(Set servItemOrdemServicos) {
        this.servItemOrdemServicos = servItemOrdemServicos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cadPessoa")
    public Set getCadVeiculoses() {
        return this.cadVeiculoses;
    }
    
    public void setCadVeiculoses(Set cadVeiculoses) {
        this.cadVeiculoses = cadVeiculoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cadPessoa")
    public Set getCadEnderecoses() {
        return this.cadEnderecoses;
    }
    
    public void setCadEnderecoses(Set cadEnderecoses) {
        this.cadEnderecoses = cadEnderecoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cadPessoa")
    public Set getCadRelServFornecs() {
        return this.cadRelServFornecs;
    }
    
    public void setCadRelServFornecs(Set cadRelServFornecs) {
        this.cadRelServFornecs = cadRelServFornecs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cadPessoa")
    public Set getServOrdemServicos() {
        return this.servOrdemServicos;
    }
    
    public void setServOrdemServicos(Set servOrdemServicos) {
        this.servOrdemServicos = servOrdemServicos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cadPessoa")
    public Set getCadRelProdFornecs() {
        return this.cadRelProdFornecs;
    }
    
    public void setCadRelProdFornecs(Set cadRelProdFornecs) {
        this.cadRelProdFornecs = cadRelProdFornecs;
    }




}


