package br.com.jvmsoftware.entities;
// Generated 31/Mar/2016 22:28:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CadProduto generated by hbm2java
 */
public class CadProduto  implements java.io.Serializable {


     private Integer idProduto;
     private PubEmbalagem pubEmbalagem;
     private PubEmpresa pubEmpresa;
     private String produto;
     private String descricao;
     private BigDecimal preco;
     private Integer qtdeEmbalagem;
     private boolean ativo;
     private Set<CadRelProdFornec> cadRelProdFornecs = new HashSet<CadRelProdFornec>(0);

    public CadProduto() {
    }

	
    public CadProduto(PubEmpresa pubEmpresa, String produto, boolean ativo) {
        this.pubEmpresa = pubEmpresa;
        this.produto = produto;
        this.ativo = ativo;
    }
    public CadProduto(PubEmbalagem pubEmbalagem, PubEmpresa pubEmpresa, String produto, String descricao, BigDecimal preco, Integer qtdeEmbalagem, boolean ativo, Set<CadRelProdFornec> cadRelProdFornecs) {
       this.pubEmbalagem = pubEmbalagem;
       this.pubEmpresa = pubEmpresa;
       this.produto = produto;
       this.descricao = descricao;
       this.preco = preco;
       this.qtdeEmbalagem = qtdeEmbalagem;
       this.ativo = ativo;
       this.cadRelProdFornecs = cadRelProdFornecs;
    }
   
    public Integer getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Integer idProduto) {
        this.idProduto = idProduto;
    }
    public PubEmbalagem getPubEmbalagem() {
        return this.pubEmbalagem;
    }
    
    public void setPubEmbalagem(PubEmbalagem pubEmbalagem) {
        this.pubEmbalagem = pubEmbalagem;
    }
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }
    public String getProduto() {
        return this.produto;
    }
    
    public void setProduto(String produto) {
        this.produto = produto;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public BigDecimal getPreco() {
        return this.preco;
    }
    
    public void setPreco(BigDecimal preco) {
        this.preco = preco;
    }
    public Integer getQtdeEmbalagem() {
        return this.qtdeEmbalagem;
    }
    
    public void setQtdeEmbalagem(Integer qtdeEmbalagem) {
        this.qtdeEmbalagem = qtdeEmbalagem;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
    public Set<CadRelProdFornec> getCadRelProdFornecs() {
        return this.cadRelProdFornecs;
    }
    
    public void setCadRelProdFornecs(Set<CadRelProdFornec> cadRelProdFornecs) {
        this.cadRelProdFornecs = cadRelProdFornecs;
    }




}


