package br.com.jvmsoftware.entities;
// Generated 4/Ago/2015 22:25:45 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CadPessoaFisica generated by hbm2java
 */
public class CadPessoaFisica  implements java.io.Serializable {


     private Integer idPessoaFisica;
     private CadPessoa cadPessoa;
     private PubEstado pubEstado;
     private PubMunicipio pubMunicipio;
     private Float cpfUsuario;
     private String nomeUsuario;
     private Date dataNascimento;
     private String endereco;
     private Float numero;
     private String bairro;
     private String complemento;
     private Float cep;

    public CadPessoaFisica() {
    }

	
    public CadPessoaFisica(CadPessoa cadPessoa, String nomeUsuario) {
        this.cadPessoa = cadPessoa;
        this.nomeUsuario = nomeUsuario;
    }
    public CadPessoaFisica(CadPessoa cadPessoa, PubEstado pubEstado, PubMunicipio pubMunicipio, Float cpfUsuario, String nomeUsuario, Date dataNascimento, String endereco, Float numero, String bairro, String complemento, Float cep) {
       this.cadPessoa = cadPessoa;
       this.pubEstado = pubEstado;
       this.pubMunicipio = pubMunicipio;
       this.cpfUsuario = cpfUsuario;
       this.nomeUsuario = nomeUsuario;
       this.dataNascimento = dataNascimento;
       this.endereco = endereco;
       this.numero = numero;
       this.bairro = bairro;
       this.complemento = complemento;
       this.cep = cep;
    }
   
    public Integer getIdPessoaFisica() {
        return this.idPessoaFisica;
    }
    
    public void setIdPessoaFisica(Integer idPessoaFisica) {
        this.idPessoaFisica = idPessoaFisica;
    }
    public CadPessoa getCadPessoa() {
        return this.cadPessoa;
    }
    
    public void setCadPessoa(CadPessoa cadPessoa) {
        this.cadPessoa = cadPessoa;
    }
    public PubEstado getPubEstado() {
        return this.pubEstado;
    }
    
    public void setPubEstado(PubEstado pubEstado) {
        this.pubEstado = pubEstado;
    }
    public PubMunicipio getPubMunicipio() {
        return this.pubMunicipio;
    }
    
    public void setPubMunicipio(PubMunicipio pubMunicipio) {
        this.pubMunicipio = pubMunicipio;
    }
    public Float getCpfUsuario() {
        return this.cpfUsuario;
    }
    
    public void setCpfUsuario(Float cpfUsuario) {
        this.cpfUsuario = cpfUsuario;
    }
    public String getNomeUsuario() {
        return this.nomeUsuario;
    }
    
    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public Float getNumero() {
        return this.numero;
    }
    
    public void setNumero(Float numero) {
        this.numero = numero;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public Float getCep() {
        return this.cep;
    }
    
    public void setCep(Float cep) {
        this.cep = cep;
    }




}


