package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CadRelServFornec generated by hbm2java
 */
@Entity
@Table(name="cad_rel_serv_fornec"
    ,catalog="jvmdsoftware"
)
public class CadRelServFornec  implements java.io.Serializable {


     private Integer idRel;
     private CadPessoa cadPessoa;
     private CadServicos cadServicos;
     private PubEmpresa pubEmpresa;
     private Double precoServico;

    public CadRelServFornec() {
    }

	
    public CadRelServFornec(CadPessoa cadPessoa, CadServicos cadServicos, PubEmpresa pubEmpresa) {
        this.cadPessoa = cadPessoa;
        this.cadServicos = cadServicos;
        this.pubEmpresa = pubEmpresa;
    }
    public CadRelServFornec(CadPessoa cadPessoa, CadServicos cadServicos, PubEmpresa pubEmpresa, Double precoServico) {
       this.cadPessoa = cadPessoa;
       this.cadServicos = cadServicos;
       this.pubEmpresa = pubEmpresa;
       this.precoServico = precoServico;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_rel", unique=true, nullable=false)
    public Integer getIdRel() {
        return this.idRel;
    }
    
    public void setIdRel(Integer idRel) {
        this.idRel = idRel;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fornecedor", nullable=false)
    public CadPessoa getCadPessoa() {
        return this.cadPessoa;
    }
    
    public void setCadPessoa(CadPessoa cadPessoa) {
        this.cadPessoa = cadPessoa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="servico", nullable=false)
    public CadServicos getCadServicos() {
        return this.cadServicos;
    }
    
    public void setCadServicos(CadServicos cadServicos) {
        this.cadServicos = cadServicos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa", nullable=false)
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }

    
    @Column(name="preco_servico", precision=10)
    public Double getPrecoServico() {
        return this.precoServico;
    }
    
    public void setPrecoServico(Double precoServico) {
        this.precoServico = precoServico;
    }




}


