package br.com.jvmsoftware.entities;
// Generated 9/Abr/2016 18:34:16 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CadRelProdFornec generated by hbm2java
 */
public class CadRelProdFornec  implements java.io.Serializable {


     private Integer idRel;
     private CadPessoa cadPessoa;
     private CadProduto cadProduto;
     private PubEmpresa pubEmpresa;
     private BigDecimal precoCompra;

    public CadRelProdFornec() {
    }

	
    public CadRelProdFornec(CadPessoa cadPessoa, CadProduto cadProduto, PubEmpresa pubEmpresa) {
        this.cadPessoa = cadPessoa;
        this.cadProduto = cadProduto;
        this.pubEmpresa = pubEmpresa;
    }
    public CadRelProdFornec(CadPessoa cadPessoa, CadProduto cadProduto, PubEmpresa pubEmpresa, BigDecimal precoCompra) {
       this.cadPessoa = cadPessoa;
       this.cadProduto = cadProduto;
       this.pubEmpresa = pubEmpresa;
       this.precoCompra = precoCompra;
    }
   
    public Integer getIdRel() {
        return this.idRel;
    }
    
    public void setIdRel(Integer idRel) {
        this.idRel = idRel;
    }
    public CadPessoa getCadPessoa() {
        return this.cadPessoa;
    }
    
    public void setCadPessoa(CadPessoa cadPessoa) {
        this.cadPessoa = cadPessoa;
    }
    public CadProduto getCadProduto() {
        return this.cadProduto;
    }
    
    public void setCadProduto(CadProduto cadProduto) {
        this.cadProduto = cadProduto;
    }
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }
    public BigDecimal getPrecoCompra() {
        return this.precoCompra;
    }
    
    public void setPrecoCompra(BigDecimal precoCompra) {
        this.precoCompra = precoCompra;
    }




}


