package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CadRelProdFornec generated by hbm2java
 */
@Entity
@Table(name="cad_rel_prod_fornec"
    ,catalog="jvmdsoftware"
)
public class CadRelProdFornec  implements java.io.Serializable {


     private Integer idRel;
     private CadPessoa cadPessoa;
     private CadProduto cadProduto;
     private PubEmpresa pubEmpresa;
     private BigDecimal precoCompra;

    public CadRelProdFornec() {
    }

	
    public CadRelProdFornec(CadPessoa cadPessoa, CadProduto cadProduto, PubEmpresa pubEmpresa) {
        this.cadPessoa = cadPessoa;
        this.cadProduto = cadProduto;
        this.pubEmpresa = pubEmpresa;
    }
    public CadRelProdFornec(CadPessoa cadPessoa, CadProduto cadProduto, PubEmpresa pubEmpresa, BigDecimal precoCompra) {
       this.cadPessoa = cadPessoa;
       this.cadProduto = cadProduto;
       this.pubEmpresa = pubEmpresa;
       this.precoCompra = precoCompra;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_rel", unique=true, nullable=false)
    public Integer getIdRel() {
        return this.idRel;
    }
    
    public void setIdRel(Integer idRel) {
        this.idRel = idRel;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fornecedor", nullable=false)
    public CadPessoa getCadPessoa() {
        return this.cadPessoa;
    }
    
    public void setCadPessoa(CadPessoa cadPessoa) {
        this.cadPessoa = cadPessoa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto", nullable=false)
    public CadProduto getCadProduto() {
        return this.cadProduto;
    }
    
    public void setCadProduto(CadProduto cadProduto) {
        this.cadProduto = cadProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa", nullable=false)
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }

    
    @Column(name="preco_compra", precision=10)
    public BigDecimal getPrecoCompra() {
        return this.precoCompra;
    }
    
    public void setPrecoCompra(BigDecimal precoCompra) {
        this.precoCompra = precoCompra;
    }




}


