package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CadServicos generated by hbm2java
 */
@Entity
@Table(name="cad_servicos"
    ,catalog="jvmdsoftware"
)
public class CadServicos  implements java.io.Serializable {


     private int idServico;
     private PubEmpresa pubEmpresa;
     private PubFrequenciaServico pubFrequenciaServico;
     private String servico;
     private String descricao;
     private BigDecimal preco;
     private boolean ativo;
     private Set comRelCompraOrdemServicos = new HashSet(0);
     private Set cadRelServFornecs = new HashSet(0);
     private Set servItemOrdemServicos = new HashSet(0);

    public CadServicos() {
    }

	
    public CadServicos(int idServico, PubEmpresa pubEmpresa, String servico, boolean ativo) {
        this.idServico = idServico;
        this.pubEmpresa = pubEmpresa;
        this.servico = servico;
        this.ativo = ativo;
    }
    public CadServicos(int idServico, PubEmpresa pubEmpresa, PubFrequenciaServico pubFrequenciaServico, String servico, String descricao, BigDecimal preco, boolean ativo, Set comRelCompraOrdemServicos, Set cadRelServFornecs, Set servItemOrdemServicos) {
       this.idServico = idServico;
       this.pubEmpresa = pubEmpresa;
       this.pubFrequenciaServico = pubFrequenciaServico;
       this.servico = servico;
       this.descricao = descricao;
       this.preco = preco;
       this.ativo = ativo;
       this.comRelCompraOrdemServicos = comRelCompraOrdemServicos;
       this.cadRelServFornecs = cadRelServFornecs;
       this.servItemOrdemServicos = servItemOrdemServicos;
    }
   
     @Id 

    
    @Column(name="id_servico", unique=true, nullable=false)
    public int getIdServico() {
        return this.idServico;
    }
    
    public void setIdServico(int idServico) {
        this.idServico = idServico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa", nullable=false)
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="frequecia_servico")
    public PubFrequenciaServico getPubFrequenciaServico() {
        return this.pubFrequenciaServico;
    }
    
    public void setPubFrequenciaServico(PubFrequenciaServico pubFrequenciaServico) {
        this.pubFrequenciaServico = pubFrequenciaServico;
    }

    
    @Column(name="servico", nullable=false, length=50)
    public String getServico() {
        return this.servico;
    }
    
    public void setServico(String servico) {
        this.servico = servico;
    }

    
    @Column(name="descricao")
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="preco", precision=10)
    public BigDecimal getPreco() {
        return this.preco;
    }
    
    public void setPreco(BigDecimal preco) {
        this.preco = preco;
    }

    
    @Column(name="ativo", nullable=false)
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cadServicos")
    public Set getComRelCompraOrdemServicos() {
        return this.comRelCompraOrdemServicos;
    }
    
    public void setComRelCompraOrdemServicos(Set comRelCompraOrdemServicos) {
        this.comRelCompraOrdemServicos = comRelCompraOrdemServicos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cadServicos")
    public Set getCadRelServFornecs() {
        return this.cadRelServFornecs;
    }
    
    public void setCadRelServFornecs(Set cadRelServFornecs) {
        this.cadRelServFornecs = cadRelServFornecs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cadServicos")
    public Set getServItemOrdemServicos() {
        return this.servItemOrdemServicos;
    }
    
    public void setServItemOrdemServicos(Set servItemOrdemServicos) {
        this.servItemOrdemServicos = servItemOrdemServicos;
    }




}


