package br.com.jvmsoftware.entities;
// Generated 11/Abr/2016 15:26:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CadServicos generated by hbm2java
 */
public class CadServicos  implements java.io.Serializable {


     private int idServico;
     private PubEmpresa pubEmpresa;
     private PubFrequenciaServico pubFrequenciaServico;
     private String servico;
     private String descricao;
     private BigDecimal preco;
     private boolean ativo;
     private Set<ComRelCompraOrdemServico> comRelCompraOrdemServicos = new HashSet<ComRelCompraOrdemServico>(0);
     private Set<CadRelServFornec> cadRelServFornecs = new HashSet<CadRelServFornec>(0);

    public CadServicos() {
    }

	
    public CadServicos(int idServico, PubEmpresa pubEmpresa, String servico, boolean ativo) {
        this.idServico = idServico;
        this.pubEmpresa = pubEmpresa;
        this.servico = servico;
        this.ativo = ativo;
    }
    public CadServicos(int idServico, PubEmpresa pubEmpresa, PubFrequenciaServico pubFrequenciaServico, String servico, String descricao, BigDecimal preco, boolean ativo, Set<ComRelCompraOrdemServico> comRelCompraOrdemServicos, Set<CadRelServFornec> cadRelServFornecs) {
       this.idServico = idServico;
       this.pubEmpresa = pubEmpresa;
       this.pubFrequenciaServico = pubFrequenciaServico;
       this.servico = servico;
       this.descricao = descricao;
       this.preco = preco;
       this.ativo = ativo;
       this.comRelCompraOrdemServicos = comRelCompraOrdemServicos;
       this.cadRelServFornecs = cadRelServFornecs;
    }
   
    public int getIdServico() {
        return this.idServico;
    }
    
    public void setIdServico(int idServico) {
        this.idServico = idServico;
    }
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }
    public PubFrequenciaServico getPubFrequenciaServico() {
        return this.pubFrequenciaServico;
    }
    
    public void setPubFrequenciaServico(PubFrequenciaServico pubFrequenciaServico) {
        this.pubFrequenciaServico = pubFrequenciaServico;
    }
    public String getServico() {
        return this.servico;
    }
    
    public void setServico(String servico) {
        this.servico = servico;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public BigDecimal getPreco() {
        return this.preco;
    }
    
    public void setPreco(BigDecimal preco) {
        this.preco = preco;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
    public Set<ComRelCompraOrdemServico> getComRelCompraOrdemServicos() {
        return this.comRelCompraOrdemServicos;
    }
    
    public void setComRelCompraOrdemServicos(Set<ComRelCompraOrdemServico> comRelCompraOrdemServicos) {
        this.comRelCompraOrdemServicos = comRelCompraOrdemServicos;
    }
    public Set<CadRelServFornec> getCadRelServFornecs() {
        return this.cadRelServFornecs;
    }
    
    public void setCadRelServFornecs(Set<CadRelServFornec> cadRelServFornecs) {
        this.cadRelServFornecs = cadRelServFornecs;
    }




}


