package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CadVeiculos generated by hbm2java
 */
@Entity
@Table(name="cad_veiculos"
    ,catalog="jvmdsoftware"
)
public class CadVeiculos  implements java.io.Serializable {


     private Integer idVeiculo;
     private CadPessoa cadPessoa;
     private PubEmpresa pubEmpresa;
     private PubMarcaVeiculo pubMarcaVeiculo;
     private PubModeloVeiculo pubModeloVeiculo;
     private PubTipoVeiculo pubTipoVeiculo;
     private String placa;
     private String chassis;
     private String observacao;
     private Set servOrdemServicos = new HashSet(0);

    public CadVeiculos() {
    }

	
    public CadVeiculos(CadPessoa cadPessoa, PubEmpresa pubEmpresa, PubTipoVeiculo pubTipoVeiculo) {
        this.cadPessoa = cadPessoa;
        this.pubEmpresa = pubEmpresa;
        this.pubTipoVeiculo = pubTipoVeiculo;
    }
    public CadVeiculos(CadPessoa cadPessoa, PubEmpresa pubEmpresa, PubMarcaVeiculo pubMarcaVeiculo, PubModeloVeiculo pubModeloVeiculo, PubTipoVeiculo pubTipoVeiculo, String placa, String chassis, String observacao, Set servOrdemServicos) {
       this.cadPessoa = cadPessoa;
       this.pubEmpresa = pubEmpresa;
       this.pubMarcaVeiculo = pubMarcaVeiculo;
       this.pubModeloVeiculo = pubModeloVeiculo;
       this.pubTipoVeiculo = pubTipoVeiculo;
       this.placa = placa;
       this.chassis = chassis;
       this.observacao = observacao;
       this.servOrdemServicos = servOrdemServicos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_veiculo", unique=true, nullable=false)
    public Integer getIdVeiculo() {
        return this.idVeiculo;
    }
    
    public void setIdVeiculo(Integer idVeiculo) {
        this.idVeiculo = idVeiculo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pessoa", nullable=false)
    public CadPessoa getCadPessoa() {
        return this.cadPessoa;
    }
    
    public void setCadPessoa(CadPessoa cadPessoa) {
        this.cadPessoa = cadPessoa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa", nullable=false)
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="marca")
    public PubMarcaVeiculo getPubMarcaVeiculo() {
        return this.pubMarcaVeiculo;
    }
    
    public void setPubMarcaVeiculo(PubMarcaVeiculo pubMarcaVeiculo) {
        this.pubMarcaVeiculo = pubMarcaVeiculo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="modelo")
    public PubModeloVeiculo getPubModeloVeiculo() {
        return this.pubModeloVeiculo;
    }
    
    public void setPubModeloVeiculo(PubModeloVeiculo pubModeloVeiculo) {
        this.pubModeloVeiculo = pubModeloVeiculo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_veiculo", nullable=false)
    public PubTipoVeiculo getPubTipoVeiculo() {
        return this.pubTipoVeiculo;
    }
    
    public void setPubTipoVeiculo(PubTipoVeiculo pubTipoVeiculo) {
        this.pubTipoVeiculo = pubTipoVeiculo;
    }

    
    @Column(name="placa", length=8)
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }

    
    @Column(name="chassis", length=30)
    public String getChassis() {
        return this.chassis;
    }
    
    public void setChassis(String chassis) {
        this.chassis = chassis;
    }

    
    @Column(name="observacao")
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cadVeiculos")
    public Set getServOrdemServicos() {
        return this.servOrdemServicos;
    }
    
    public void setServOrdemServicos(Set servOrdemServicos) {
        this.servOrdemServicos = servOrdemServicos;
    }




}


