package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComCompraOrdem generated by hbm2java
 */
@Entity
@Table(name="com_compra_ordem"
    ,catalog="jvmdsoftware"
)
public class ComCompraOrdem  implements java.io.Serializable {


     private int id;
     private PubEmpresa pubEmpresa;
     private PubUsuario pubUsuario;
     private WflWorkflow wflWorkflow;
     private Date dataHoraInclusao;
     private Set comRelCompraOrdemProdutos = new HashSet(0);
     private Set comRelCompraOrdemServicos = new HashSet(0);

    public ComCompraOrdem() {
    }

	
    public ComCompraOrdem(int id, PubEmpresa pubEmpresa, PubUsuario pubUsuario, WflWorkflow wflWorkflow, Date dataHoraInclusao) {
        this.id = id;
        this.pubEmpresa = pubEmpresa;
        this.pubUsuario = pubUsuario;
        this.wflWorkflow = wflWorkflow;
        this.dataHoraInclusao = dataHoraInclusao;
    }
    public ComCompraOrdem(int id, PubEmpresa pubEmpresa, PubUsuario pubUsuario, WflWorkflow wflWorkflow, Date dataHoraInclusao, Set comRelCompraOrdemProdutos, Set comRelCompraOrdemServicos) {
       this.id = id;
       this.pubEmpresa = pubEmpresa;
       this.pubUsuario = pubUsuario;
       this.wflWorkflow = wflWorkflow;
       this.dataHoraInclusao = dataHoraInclusao;
       this.comRelCompraOrdemProdutos = comRelCompraOrdemProdutos;
       this.comRelCompraOrdemServicos = comRelCompraOrdemServicos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa", nullable=false)
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_inclusao", nullable=false)
    public PubUsuario getPubUsuario() {
        return this.pubUsuario;
    }
    
    public void setPubUsuario(PubUsuario pubUsuario) {
        this.pubUsuario = pubUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="workflow", nullable=false)
    public WflWorkflow getWflWorkflow() {
        return this.wflWorkflow;
    }
    
    public void setWflWorkflow(WflWorkflow wflWorkflow) {
        this.wflWorkflow = wflWorkflow;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_hora_inclusao", nullable=false, length=19)
    public Date getDataHoraInclusao() {
        return this.dataHoraInclusao;
    }
    
    public void setDataHoraInclusao(Date dataHoraInclusao) {
        this.dataHoraInclusao = dataHoraInclusao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comCompraOrdem")
    public Set getComRelCompraOrdemProdutos() {
        return this.comRelCompraOrdemProdutos;
    }
    
    public void setComRelCompraOrdemProdutos(Set comRelCompraOrdemProdutos) {
        this.comRelCompraOrdemProdutos = comRelCompraOrdemProdutos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comCompraOrdem")
    public Set getComRelCompraOrdemServicos() {
        return this.comRelCompraOrdemServicos;
    }
    
    public void setComRelCompraOrdemServicos(Set comRelCompraOrdemServicos) {
        this.comRelCompraOrdemServicos = comRelCompraOrdemServicos;
    }




}


