package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComRelVendaProduto generated by hbm2java
 */
@Entity
@Table(name="com_rel_venda_produto"
    ,catalog="jvmdsoftware"
)
public class ComRelVendaProduto  implements java.io.Serializable {


     private int idRel;
     private CadProduto cadProduto;
     private ComVendaPedido comVendaPedido;

    public ComRelVendaProduto() {
    }

    public ComRelVendaProduto(int idRel, CadProduto cadProduto, ComVendaPedido comVendaPedido) {
       this.idRel = idRel;
       this.cadProduto = cadProduto;
       this.comVendaPedido = comVendaPedido;
    }
   
     @Id 

    
    @Column(name="id_rel", unique=true, nullable=false)
    public int getIdRel() {
        return this.idRel;
    }
    
    public void setIdRel(int idRel) {
        this.idRel = idRel;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto", nullable=false)
    public CadProduto getCadProduto() {
        return this.cadProduto;
    }
    
    public void setCadProduto(CadProduto cadProduto) {
        this.cadProduto = cadProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="venda_pedido", nullable=false)
    public ComVendaPedido getComVendaPedido() {
        return this.comVendaPedido;
    }
    
    public void setComVendaPedido(ComVendaPedido comVendaPedido) {
        this.comVendaPedido = comVendaPedido;
    }




}


