package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComRelCompraOrdemServico generated by hbm2java
 */
@Entity
@Table(name="com_rel_compra_ordem_servico"
    ,catalog="jvmdsoftware"
)
public class ComRelCompraOrdemServico  implements java.io.Serializable {


     private int idRel;
     private CadServicos cadServicos;
     private ComCompraOrdem comCompraOrdem;

    public ComRelCompraOrdemServico() {
    }

    public ComRelCompraOrdemServico(int idRel, CadServicos cadServicos, ComCompraOrdem comCompraOrdem) {
       this.idRel = idRel;
       this.cadServicos = cadServicos;
       this.comCompraOrdem = comCompraOrdem;
    }
   
     @Id 

    
    @Column(name="id_rel", unique=true, nullable=false)
    public int getIdRel() {
        return this.idRel;
    }
    
    public void setIdRel(int idRel) {
        this.idRel = idRel;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="servico", nullable=false)
    public CadServicos getCadServicos() {
        return this.cadServicos;
    }
    
    public void setCadServicos(CadServicos cadServicos) {
        this.cadServicos = cadServicos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ordem_compra", nullable=false)
    public ComCompraOrdem getComCompraOrdem() {
        return this.comCompraOrdem;
    }
    
    public void setComCompraOrdem(ComCompraOrdem comCompraOrdem) {
        this.comCompraOrdem = comCompraOrdem;
    }




}


