package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComVendaPedido generated by hbm2java
 */
@Entity
@Table(name="com_venda_pedido"
    ,catalog="jvmdsoftware"
)
public class ComVendaPedido  implements java.io.Serializable {


     private int idPedido;
     private int empresa;
     private int usuario;
     private Date dataHora;
     private int workflow;
     private Set comRelVendaProdutos = new HashSet(0);

    public ComVendaPedido() {
    }

	
    public ComVendaPedido(int idPedido, int empresa, int usuario, Date dataHora, int workflow) {
        this.idPedido = idPedido;
        this.empresa = empresa;
        this.usuario = usuario;
        this.dataHora = dataHora;
        this.workflow = workflow;
    }
    public ComVendaPedido(int idPedido, int empresa, int usuario, Date dataHora, int workflow, Set comRelVendaProdutos) {
       this.idPedido = idPedido;
       this.empresa = empresa;
       this.usuario = usuario;
       this.dataHora = dataHora;
       this.workflow = workflow;
       this.comRelVendaProdutos = comRelVendaProdutos;
    }
   
     @Id 

    
    @Column(name="id_pedido", unique=true, nullable=false)
    public int getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }

    
    @Column(name="empresa", nullable=false)
    public int getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(int empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="usuario", nullable=false)
    public int getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(int usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_hora", nullable=false, length=19)
    public Date getDataHora() {
        return this.dataHora;
    }
    
    public void setDataHora(Date dataHora) {
        this.dataHora = dataHora;
    }

    
    @Column(name="workflow", nullable=false)
    public int getWorkflow() {
        return this.workflow;
    }
    
    public void setWorkflow(int workflow) {
        this.workflow = workflow;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comVendaPedido")
    public Set getComRelVendaProdutos() {
        return this.comRelVendaProdutos;
    }
    
    public void setComRelVendaProdutos(Set comRelVendaProdutos) {
        this.comRelVendaProdutos = comRelVendaProdutos;
    }




}


