package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CtrLog generated by hbm2java
 */
@Entity
@Table(name="ctr_log"
    ,catalog="jvmdsoftware"
)
public class CtrLog  implements java.io.Serializable {


     private Integer idLog;
     private PubSistema pubSistema;
     private PubUsuario pubUsuario;
     private Date dataHora;
     private String tread;
     private String log;

    public CtrLog() {
    }

	
    public CtrLog(PubSistema pubSistema, PubUsuario pubUsuario, Date dataHora) {
        this.pubSistema = pubSistema;
        this.pubUsuario = pubUsuario;
        this.dataHora = dataHora;
    }
    public CtrLog(PubSistema pubSistema, PubUsuario pubUsuario, Date dataHora, String tread, String log) {
       this.pubSistema = pubSistema;
       this.pubUsuario = pubUsuario;
       this.dataHora = dataHora;
       this.tread = tread;
       this.log = log;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_log", unique=true, nullable=false)
    public Integer getIdLog() {
        return this.idLog;
    }
    
    public void setIdLog(Integer idLog) {
        this.idLog = idLog;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sistema", nullable=false)
    public PubSistema getPubSistema() {
        return this.pubSistema;
    }
    
    public void setPubSistema(PubSistema pubSistema) {
        this.pubSistema = pubSistema;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario", nullable=false)
    public PubUsuario getPubUsuario() {
        return this.pubUsuario;
    }
    
    public void setPubUsuario(PubUsuario pubUsuario) {
        this.pubUsuario = pubUsuario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_hora", nullable=false, length=19)
    public Date getDataHora() {
        return this.dataHora;
    }
    
    public void setDataHora(Date dataHora) {
        this.dataHora = dataHora;
    }

    
    @Column(name="tread", length=30)
    public String getTread() {
        return this.tread;
    }
    
    public void setTread(String tread) {
        this.tread = tread;
    }

    
    @Column(name="log", length=500)
    public String getLog() {
        return this.log;
    }
    
    public void setLog(String log) {
        this.log = log;
    }




}


