package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PubConteudo generated by hbm2java
 */
@Entity
@Table(name="pub_conteudo"
    ,catalog="jvmdsoftware"
)
public class PubConteudo  implements java.io.Serializable {


     private Integer idConteudo;
     private PubMenu pubMenu;
     private PubPosicao pubPosicao;
     private String conteudo;
     private Date inicioExibicao;
     private Date fimExibicao;

    public PubConteudo() {
    }

	
    public PubConteudo(PubMenu pubMenu, PubPosicao pubPosicao, String conteudo, Date inicioExibicao) {
        this.pubMenu = pubMenu;
        this.pubPosicao = pubPosicao;
        this.conteudo = conteudo;
        this.inicioExibicao = inicioExibicao;
    }
    public PubConteudo(PubMenu pubMenu, PubPosicao pubPosicao, String conteudo, Date inicioExibicao, Date fimExibicao) {
       this.pubMenu = pubMenu;
       this.pubPosicao = pubPosicao;
       this.conteudo = conteudo;
       this.inicioExibicao = inicioExibicao;
       this.fimExibicao = fimExibicao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_conteudo", unique=true, nullable=false)
    public Integer getIdConteudo() {
        return this.idConteudo;
    }
    
    public void setIdConteudo(Integer idConteudo) {
        this.idConteudo = idConteudo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="menu", nullable=false)
    public PubMenu getPubMenu() {
        return this.pubMenu;
    }
    
    public void setPubMenu(PubMenu pubMenu) {
        this.pubMenu = pubMenu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="posicao", nullable=false)
    public PubPosicao getPubPosicao() {
        return this.pubPosicao;
    }
    
    public void setPubPosicao(PubPosicao pubPosicao) {
        this.pubPosicao = pubPosicao;
    }

    
    @Column(name="conteudo", nullable=false, length=65535)
    public String getConteudo() {
        return this.conteudo;
    }
    
    public void setConteudo(String conteudo) {
        this.conteudo = conteudo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="inicio_exibicao", nullable=false, length=10)
    public Date getInicioExibicao() {
        return this.inicioExibicao;
    }
    
    public void setInicioExibicao(Date inicioExibicao) {
        this.inicioExibicao = inicioExibicao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fim_exibicao", length=10)
    public Date getFimExibicao() {
        return this.fimExibicao;
    }
    
    public void setFimExibicao(Date fimExibicao) {
        this.fimExibicao = fimExibicao;
    }




}


