package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PubConfigEmpresa generated by hbm2java
 */
@Entity
@Table(name="pub_config_empresa"
    ,catalog="jvmdsoftware"
)
public class PubConfigEmpresa  implements java.io.Serializable {


     private Integer idConfig;
     private PubEmpresa pubEmpresa;
     private PubTipoEmpresa pubTipoEmpresa;
     private PubTipoNegocio pubTipoNegocio;
     private String mailEnvio;
     private String mailEnvioUsuario;
     private String mailEnvioSenha;
     private String mailEnvioSmtp;
     private Integer mailEnvioPorta;

    public PubConfigEmpresa() {
    }

	
    public PubConfigEmpresa(PubEmpresa pubEmpresa, PubTipoEmpresa pubTipoEmpresa, PubTipoNegocio pubTipoNegocio) {
        this.pubEmpresa = pubEmpresa;
        this.pubTipoEmpresa = pubTipoEmpresa;
        this.pubTipoNegocio = pubTipoNegocio;
    }
    public PubConfigEmpresa(PubEmpresa pubEmpresa, PubTipoEmpresa pubTipoEmpresa, PubTipoNegocio pubTipoNegocio, String mailEnvio, String mailEnvioUsuario, String mailEnvioSenha, String mailEnvioSmtp, Integer mailEnvioPorta) {
       this.pubEmpresa = pubEmpresa;
       this.pubTipoEmpresa = pubTipoEmpresa;
       this.pubTipoNegocio = pubTipoNegocio;
       this.mailEnvio = mailEnvio;
       this.mailEnvioUsuario = mailEnvioUsuario;
       this.mailEnvioSenha = mailEnvioSenha;
       this.mailEnvioSmtp = mailEnvioSmtp;
       this.mailEnvioPorta = mailEnvioPorta;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_config", unique=true, nullable=false)
    public Integer getIdConfig() {
        return this.idConfig;
    }
    
    public void setIdConfig(Integer idConfig) {
        this.idConfig = idConfig;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa", nullable=false)
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_empresa", nullable=false)
    public PubTipoEmpresa getPubTipoEmpresa() {
        return this.pubTipoEmpresa;
    }
    
    public void setPubTipoEmpresa(PubTipoEmpresa pubTipoEmpresa) {
        this.pubTipoEmpresa = pubTipoEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_negocio", nullable=false)
    public PubTipoNegocio getPubTipoNegocio() {
        return this.pubTipoNegocio;
    }
    
    public void setPubTipoNegocio(PubTipoNegocio pubTipoNegocio) {
        this.pubTipoNegocio = pubTipoNegocio;
    }

    
    @Column(name="mail_envio", length=100)
    public String getMailEnvio() {
        return this.mailEnvio;
    }
    
    public void setMailEnvio(String mailEnvio) {
        this.mailEnvio = mailEnvio;
    }

    
    @Column(name="mail_envio_usuario", length=100)
    public String getMailEnvioUsuario() {
        return this.mailEnvioUsuario;
    }
    
    public void setMailEnvioUsuario(String mailEnvioUsuario) {
        this.mailEnvioUsuario = mailEnvioUsuario;
    }

    
    @Column(name="mail_envio_senha")
    public String getMailEnvioSenha() {
        return this.mailEnvioSenha;
    }
    
    public void setMailEnvioSenha(String mailEnvioSenha) {
        this.mailEnvioSenha = mailEnvioSenha;
    }

    
    @Column(name="mail_envio_smtp", length=100)
    public String getMailEnvioSmtp() {
        return this.mailEnvioSmtp;
    }
    
    public void setMailEnvioSmtp(String mailEnvioSmtp) {
        this.mailEnvioSmtp = mailEnvioSmtp;
    }

    
    @Column(name="mail_envio_porta")
    public Integer getMailEnvioPorta() {
        return this.mailEnvioPorta;
    }
    
    public void setMailEnvioPorta(Integer mailEnvioPorta) {
        this.mailEnvioPorta = mailEnvioPorta;
    }




}


