package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PubEmbalagem generated by hbm2java
 */
@Entity
@Table(name="pub_embalagem"
    ,catalog="jvmdsoftware"
)
public class PubEmbalagem  implements java.io.Serializable {


     private Integer idEmbalagem;
     private String embalagem;
     private Set cadProdutos = new HashSet(0);

    public PubEmbalagem() {
    }

	
    public PubEmbalagem(String embalagem) {
        this.embalagem = embalagem;
    }
    public PubEmbalagem(String embalagem, Set cadProdutos) {
       this.embalagem = embalagem;
       this.cadProdutos = cadProdutos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_embalagem", unique=true, nullable=false)
    public Integer getIdEmbalagem() {
        return this.idEmbalagem;
    }
    
    public void setIdEmbalagem(Integer idEmbalagem) {
        this.idEmbalagem = idEmbalagem;
    }

    
    @Column(name="embalagem", nullable=false, length=20)
    public String getEmbalagem() {
        return this.embalagem;
    }
    
    public void setEmbalagem(String embalagem) {
        this.embalagem = embalagem;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubEmbalagem")
    public Set getCadProdutos() {
        return this.cadProdutos;
    }
    
    public void setCadProdutos(Set cadProdutos) {
        this.cadProdutos = cadProdutos;
    }




}


