package br.com.jvmsoftware.entities;
// Generated 27/Mar/2016 8:26:38 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PubEmpresa generated by hbm2java
 */
public class PubEmpresa  implements java.io.Serializable {


     private Integer idEmpresa;
     private PubEstado pubEstado;
     private PubMunicipio pubMunicipio;
     private PubTipoCadastro pubTipoCadastro;
     private String cnpjEmpresa;
     private String razaoSocial;
     private String fantasia;
     private Double cep;
     private String endereco;
     private Double numero;
     private String bairro;
     private String complemento;
     private Date dataCadastro;
     private boolean ativo;
     private Double telefone;
     private String emailResponsavel;
     private Set<WflSituacao> wflSituacaos = new HashSet<WflSituacao>(0);
     private Set<PubConfigEmpresa> pubConfigEmpresas = new HashSet<PubConfigEmpresa>(0);
     private Set<SupSolicitacao> supSolicitacaos = new HashSet<SupSolicitacao>(0);
     private Set<AcsUsuarioSistema> acsUsuarioSistemas = new HashSet<AcsUsuarioSistema>(0);
     private Set<WflWorkflow> wflWorkflowsForEmpresaDestino = new HashSet<WflWorkflow>(0);
     private Set<CadPessoa> cadPessoas = new HashSet<CadPessoa>(0);
     private Set<WflWorkflowEvento> wflWorkflowEventos = new HashSet<WflWorkflowEvento>(0);
     private Set<AcsEmpresaSistema> acsEmpresaSistemas = new HashSet<AcsEmpresaSistema>(0);
     private Set<SupProjeto> supProjetos = new HashSet<SupProjeto>(0);
     private Set<PubUsuario> pubUsuarios = new HashSet<PubUsuario>(0);
     private Set<WflWorkflow> wflWorkflowsForEmpresaCriacao = new HashSet<WflWorkflow>(0);

    public PubEmpresa() {
    }

	
    public PubEmpresa(PubEstado pubEstado, PubMunicipio pubMunicipio, PubTipoCadastro pubTipoCadastro, String razaoSocial, String fantasia, boolean ativo) {
        this.pubEstado = pubEstado;
        this.pubMunicipio = pubMunicipio;
        this.pubTipoCadastro = pubTipoCadastro;
        this.razaoSocial = razaoSocial;
        this.fantasia = fantasia;
        this.ativo = ativo;
    }
    public PubEmpresa(PubEstado pubEstado, PubMunicipio pubMunicipio, PubTipoCadastro pubTipoCadastro, String cnpjEmpresa, String razaoSocial, String fantasia, Double cep, String endereco, Double numero, String bairro, String complemento, Date dataCadastro, boolean ativo, Double telefone, String emailResponsavel, Set<WflSituacao> wflSituacaos, Set<PubConfigEmpresa> pubConfigEmpresas, Set<SupSolicitacao> supSolicitacaos, Set<AcsUsuarioSistema> acsUsuarioSistemas, Set<WflWorkflow> wflWorkflowsForEmpresaDestino, Set<CadPessoa> cadPessoas, Set<WflWorkflowEvento> wflWorkflowEventos, Set<AcsEmpresaSistema> acsEmpresaSistemas, Set<SupProjeto> supProjetos, Set<PubUsuario> pubUsuarios, Set<WflWorkflow> wflWorkflowsForEmpresaCriacao) {
       this.pubEstado = pubEstado;
       this.pubMunicipio = pubMunicipio;
       this.pubTipoCadastro = pubTipoCadastro;
       this.cnpjEmpresa = cnpjEmpresa;
       this.razaoSocial = razaoSocial;
       this.fantasia = fantasia;
       this.cep = cep;
       this.endereco = endereco;
       this.numero = numero;
       this.bairro = bairro;
       this.complemento = complemento;
       this.dataCadastro = dataCadastro;
       this.ativo = ativo;
       this.telefone = telefone;
       this.emailResponsavel = emailResponsavel;
       this.wflSituacaos = wflSituacaos;
       this.pubConfigEmpresas = pubConfigEmpresas;
       this.supSolicitacaos = supSolicitacaos;
       this.acsUsuarioSistemas = acsUsuarioSistemas;
       this.wflWorkflowsForEmpresaDestino = wflWorkflowsForEmpresaDestino;
       this.cadPessoas = cadPessoas;
       this.wflWorkflowEventos = wflWorkflowEventos;
       this.acsEmpresaSistemas = acsEmpresaSistemas;
       this.supProjetos = supProjetos;
       this.pubUsuarios = pubUsuarios;
       this.wflWorkflowsForEmpresaCriacao = wflWorkflowsForEmpresaCriacao;
    }
   
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public PubEstado getPubEstado() {
        return this.pubEstado;
    }
    
    public void setPubEstado(PubEstado pubEstado) {
        this.pubEstado = pubEstado;
    }
    public PubMunicipio getPubMunicipio() {
        return this.pubMunicipio;
    }
    
    public void setPubMunicipio(PubMunicipio pubMunicipio) {
        this.pubMunicipio = pubMunicipio;
    }
    public PubTipoCadastro getPubTipoCadastro() {
        return this.pubTipoCadastro;
    }
    
    public void setPubTipoCadastro(PubTipoCadastro pubTipoCadastro) {
        this.pubTipoCadastro = pubTipoCadastro;
    }
    public String getCnpjEmpresa() {
        return this.cnpjEmpresa;
    }
    
    public void setCnpjEmpresa(String cnpjEmpresa) {
        this.cnpjEmpresa = cnpjEmpresa;
    }
    public String getRazaoSocial() {
        return this.razaoSocial;
    }
    
    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }
    public String getFantasia() {
        return this.fantasia;
    }
    
    public void setFantasia(String fantasia) {
        this.fantasia = fantasia;
    }
    public Double getCep() {
        return this.cep;
    }
    
    public void setCep(Double cep) {
        this.cep = cep;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public Double getNumero() {
        return this.numero;
    }
    
    public void setNumero(Double numero) {
        this.numero = numero;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
    public Double getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(Double telefone) {
        this.telefone = telefone;
    }
    public String getEmailResponsavel() {
        return this.emailResponsavel;
    }
    
    public void setEmailResponsavel(String emailResponsavel) {
        this.emailResponsavel = emailResponsavel;
    }
    public Set<WflSituacao> getWflSituacaos() {
        return this.wflSituacaos;
    }
    
    public void setWflSituacaos(Set<WflSituacao> wflSituacaos) {
        this.wflSituacaos = wflSituacaos;
    }
    public Set<PubConfigEmpresa> getPubConfigEmpresas() {
        return this.pubConfigEmpresas;
    }
    
    public void setPubConfigEmpresas(Set<PubConfigEmpresa> pubConfigEmpresas) {
        this.pubConfigEmpresas = pubConfigEmpresas;
    }
    public Set<SupSolicitacao> getSupSolicitacaos() {
        return this.supSolicitacaos;
    }
    
    public void setSupSolicitacaos(Set<SupSolicitacao> supSolicitacaos) {
        this.supSolicitacaos = supSolicitacaos;
    }
    public Set<AcsUsuarioSistema> getAcsUsuarioSistemas() {
        return this.acsUsuarioSistemas;
    }
    
    public void setAcsUsuarioSistemas(Set<AcsUsuarioSistema> acsUsuarioSistemas) {
        this.acsUsuarioSistemas = acsUsuarioSistemas;
    }
    public Set<WflWorkflow> getWflWorkflowsForEmpresaDestino() {
        return this.wflWorkflowsForEmpresaDestino;
    }
    
    public void setWflWorkflowsForEmpresaDestino(Set<WflWorkflow> wflWorkflowsForEmpresaDestino) {
        this.wflWorkflowsForEmpresaDestino = wflWorkflowsForEmpresaDestino;
    }
    public Set<CadPessoa> getCadPessoas() {
        return this.cadPessoas;
    }
    
    public void setCadPessoas(Set<CadPessoa> cadPessoas) {
        this.cadPessoas = cadPessoas;
    }
    public Set<WflWorkflowEvento> getWflWorkflowEventos() {
        return this.wflWorkflowEventos;
    }
    
    public void setWflWorkflowEventos(Set<WflWorkflowEvento> wflWorkflowEventos) {
        this.wflWorkflowEventos = wflWorkflowEventos;
    }
    public Set<AcsEmpresaSistema> getAcsEmpresaSistemas() {
        return this.acsEmpresaSistemas;
    }
    
    public void setAcsEmpresaSistemas(Set<AcsEmpresaSistema> acsEmpresaSistemas) {
        this.acsEmpresaSistemas = acsEmpresaSistemas;
    }
    public Set<SupProjeto> getSupProjetos() {
        return this.supProjetos;
    }
    
    public void setSupProjetos(Set<SupProjeto> supProjetos) {
        this.supProjetos = supProjetos;
    }
    public Set<PubUsuario> getPubUsuarios() {
        return this.pubUsuarios;
    }
    
    public void setPubUsuarios(Set<PubUsuario> pubUsuarios) {
        this.pubUsuarios = pubUsuarios;
    }
    public Set<WflWorkflow> getWflWorkflowsForEmpresaCriacao() {
        return this.wflWorkflowsForEmpresaCriacao;
    }
    
    public void setWflWorkflowsForEmpresaCriacao(Set<WflWorkflow> wflWorkflowsForEmpresaCriacao) {
        this.wflWorkflowsForEmpresaCriacao = wflWorkflowsForEmpresaCriacao;
    }




}


