package br.com.jvmsoftware.entities;
// Generated 11/Abr/2016 15:26:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PubEmbalagem generated by hbm2java
 */
public class PubEmbalagem  implements java.io.Serializable {


     private Integer idEmbalagem;
     private String embalagem;
     private Set<CadProduto> cadProdutos = new HashSet<CadProduto>(0);

    public PubEmbalagem() {
    }

	
    public PubEmbalagem(String embalagem) {
        this.embalagem = embalagem;
    }
    public PubEmbalagem(String embalagem, Set<CadProduto> cadProdutos) {
       this.embalagem = embalagem;
       this.cadProdutos = cadProdutos;
    }
   
    public Integer getIdEmbalagem() {
        return this.idEmbalagem;
    }
    
    public void setIdEmbalagem(Integer idEmbalagem) {
        this.idEmbalagem = idEmbalagem;
    }
    public String getEmbalagem() {
        return this.embalagem;
    }
    
    public void setEmbalagem(String embalagem) {
        this.embalagem = embalagem;
    }
    public Set<CadProduto> getCadProdutos() {
        return this.cadProdutos;
    }
    
    public void setCadProdutos(Set<CadProduto> cadProdutos) {
        this.cadProdutos = cadProdutos;
    }




}


