package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PubEstado generated by hbm2java
 */
@Entity
@Table(name="pub_estado"
    ,catalog="jvmdsoftware"
)
public class PubEstado  implements java.io.Serializable {


     private int idEstado;
     private String estado;
     private String uf;
     private Set cadEnderecoses = new HashSet(0);
     private Set pubUsuarios = new HashSet(0);
     private Set pubEmpresas = new HashSet(0);
     private Set pubMunicipios = new HashSet(0);

    public PubEstado() {
    }

	
    public PubEstado(int idEstado, String estado, String uf) {
        this.idEstado = idEstado;
        this.estado = estado;
        this.uf = uf;
    }
    public PubEstado(int idEstado, String estado, String uf, Set cadEnderecoses, Set pubUsuarios, Set pubEmpresas, Set pubMunicipios) {
       this.idEstado = idEstado;
       this.estado = estado;
       this.uf = uf;
       this.cadEnderecoses = cadEnderecoses;
       this.pubUsuarios = pubUsuarios;
       this.pubEmpresas = pubEmpresas;
       this.pubMunicipios = pubMunicipios;
    }
   
     @Id 

    
    @Column(name="id_estado", unique=true, nullable=false)
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }

    
    @Column(name="estado", nullable=false, length=150)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="UF", nullable=false, length=2)
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubEstado")
    public Set getCadEnderecoses() {
        return this.cadEnderecoses;
    }
    
    public void setCadEnderecoses(Set cadEnderecoses) {
        this.cadEnderecoses = cadEnderecoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubEstado")
    public Set getPubUsuarios() {
        return this.pubUsuarios;
    }
    
    public void setPubUsuarios(Set pubUsuarios) {
        this.pubUsuarios = pubUsuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubEstado")
    public Set getPubEmpresas() {
        return this.pubEmpresas;
    }
    
    public void setPubEmpresas(Set pubEmpresas) {
        this.pubEmpresas = pubEmpresas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubEstado")
    public Set getPubMunicipios() {
        return this.pubMunicipios;
    }
    
    public void setPubMunicipios(Set pubMunicipios) {
        this.pubMunicipios = pubMunicipios;
    }




}


