package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PubFrequenciaServico generated by hbm2java
 */
@Entity
@Table(name="pub_frequencia_servico"
    ,catalog="jvmdsoftware"
)
public class PubFrequenciaServico  implements java.io.Serializable {


     private Integer idFrequencia;
     private String frequencia;
     private String descricaoFrequencia;
     private Set cadServicoses = new HashSet(0);

    public PubFrequenciaServico() {
    }

    public PubFrequenciaServico(String frequencia, String descricaoFrequencia, Set cadServicoses) {
       this.frequencia = frequencia;
       this.descricaoFrequencia = descricaoFrequencia;
       this.cadServicoses = cadServicoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_frequencia", unique=true, nullable=false)
    public Integer getIdFrequencia() {
        return this.idFrequencia;
    }
    
    public void setIdFrequencia(Integer idFrequencia) {
        this.idFrequencia = idFrequencia;
    }

    
    @Column(name="frequencia", length=1)
    public String getFrequencia() {
        return this.frequencia;
    }
    
    public void setFrequencia(String frequencia) {
        this.frequencia = frequencia;
    }

    
    @Column(name="descricao_frequencia", length=100)
    public String getDescricaoFrequencia() {
        return this.descricaoFrequencia;
    }
    
    public void setDescricaoFrequencia(String descricaoFrequencia) {
        this.descricaoFrequencia = descricaoFrequencia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubFrequenciaServico")
    public Set getCadServicoses() {
        return this.cadServicoses;
    }
    
    public void setCadServicoses(Set cadServicoses) {
        this.cadServicoses = cadServicoses;
    }




}


