package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PubModeloVeiculo generated by hbm2java
 */
@Entity
@Table(name="pub_modelo_veiculo"
    ,catalog="jvmdsoftware"
)
public class PubModeloVeiculo  implements java.io.Serializable {


     private Integer idModeloVeiculo;
     private PubMarcaVeiculo pubMarcaVeiculo;
     private String modeloVeiculo;
     private Set cadVeiculoses = new HashSet(0);

    public PubModeloVeiculo() {
    }

	
    public PubModeloVeiculo(PubMarcaVeiculo pubMarcaVeiculo, String modeloVeiculo) {
        this.pubMarcaVeiculo = pubMarcaVeiculo;
        this.modeloVeiculo = modeloVeiculo;
    }
    public PubModeloVeiculo(PubMarcaVeiculo pubMarcaVeiculo, String modeloVeiculo, Set cadVeiculoses) {
       this.pubMarcaVeiculo = pubMarcaVeiculo;
       this.modeloVeiculo = modeloVeiculo;
       this.cadVeiculoses = cadVeiculoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_modelo_veiculo", unique=true, nullable=false)
    public Integer getIdModeloVeiculo() {
        return this.idModeloVeiculo;
    }
    
    public void setIdModeloVeiculo(Integer idModeloVeiculo) {
        this.idModeloVeiculo = idModeloVeiculo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="marca_veiculo", nullable=false)
    public PubMarcaVeiculo getPubMarcaVeiculo() {
        return this.pubMarcaVeiculo;
    }
    
    public void setPubMarcaVeiculo(PubMarcaVeiculo pubMarcaVeiculo) {
        this.pubMarcaVeiculo = pubMarcaVeiculo;
    }

    
    @Column(name="modelo_veiculo", nullable=false, length=50)
    public String getModeloVeiculo() {
        return this.modeloVeiculo;
    }
    
    public void setModeloVeiculo(String modeloVeiculo) {
        this.modeloVeiculo = modeloVeiculo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubModeloVeiculo")
    public Set getCadVeiculoses() {
        return this.cadVeiculoses;
    }
    
    public void setCadVeiculoses(Set cadVeiculoses) {
        this.cadVeiculoses = cadVeiculoses;
    }




}


