package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PubMarcaVeiculo generated by hbm2java
 */
@Entity
@Table(name="pub_marca_veiculo"
    ,catalog="jvmdsoftware"
)
public class PubMarcaVeiculo  implements java.io.Serializable {


     private Integer idMarcaVeiculo;
     private PubTipoVeiculo pubTipoVeiculo;
     private String marcaVeiculo;
     private Set cadVeiculoses = new HashSet(0);
     private Set pubModeloVeiculos = new HashSet(0);

    public PubMarcaVeiculo() {
    }

	
    public PubMarcaVeiculo(PubTipoVeiculo pubTipoVeiculo, String marcaVeiculo) {
        this.pubTipoVeiculo = pubTipoVeiculo;
        this.marcaVeiculo = marcaVeiculo;
    }
    public PubMarcaVeiculo(PubTipoVeiculo pubTipoVeiculo, String marcaVeiculo, Set cadVeiculoses, Set pubModeloVeiculos) {
       this.pubTipoVeiculo = pubTipoVeiculo;
       this.marcaVeiculo = marcaVeiculo;
       this.cadVeiculoses = cadVeiculoses;
       this.pubModeloVeiculos = pubModeloVeiculos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_marca_veiculo", unique=true, nullable=false)
    public Integer getIdMarcaVeiculo() {
        return this.idMarcaVeiculo;
    }
    
    public void setIdMarcaVeiculo(Integer idMarcaVeiculo) {
        this.idMarcaVeiculo = idMarcaVeiculo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tipo_veiculo", nullable=false)
    public PubTipoVeiculo getPubTipoVeiculo() {
        return this.pubTipoVeiculo;
    }
    
    public void setPubTipoVeiculo(PubTipoVeiculo pubTipoVeiculo) {
        this.pubTipoVeiculo = pubTipoVeiculo;
    }

    
    @Column(name="marca_veiculo", nullable=false, length=50)
    public String getMarcaVeiculo() {
        return this.marcaVeiculo;
    }
    
    public void setMarcaVeiculo(String marcaVeiculo) {
        this.marcaVeiculo = marcaVeiculo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubMarcaVeiculo")
    public Set getCadVeiculoses() {
        return this.cadVeiculoses;
    }
    
    public void setCadVeiculoses(Set cadVeiculoses) {
        this.cadVeiculoses = cadVeiculoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubMarcaVeiculo")
    public Set getPubModeloVeiculos() {
        return this.pubModeloVeiculos;
    }
    
    public void setPubModeloVeiculos(Set pubModeloVeiculos) {
        this.pubModeloVeiculos = pubModeloVeiculos;
    }




}


