package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PubMenu generated by hbm2java
 */
@Entity
@Table(name="pub_menu"
    ,catalog="jvmdsoftware"
)
public class PubMenu  implements java.io.Serializable {


     private Integer idMenu;
     private PubMenu pubMenu;
     private PubSistema pubSistema;
     private String menu;
     private String descricao;
     private String caminho;
     private String icone;
     private Set pubConteudos = new HashSet(0);
     private Set pubMenus = new HashSet(0);

    public PubMenu() {
    }

	
    public PubMenu(PubSistema pubSistema, String menu, String descricao) {
        this.pubSistema = pubSistema;
        this.menu = menu;
        this.descricao = descricao;
    }
    public PubMenu(PubMenu pubMenu, PubSistema pubSistema, String menu, String descricao, String caminho, String icone, Set pubConteudos, Set pubMenus) {
       this.pubMenu = pubMenu;
       this.pubSistema = pubSistema;
       this.menu = menu;
       this.descricao = descricao;
       this.caminho = caminho;
       this.icone = icone;
       this.pubConteudos = pubConteudos;
       this.pubMenus = pubMenus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_menu", unique=true, nullable=false)
    public Integer getIdMenu() {
        return this.idMenu;
    }
    
    public void setIdMenu(Integer idMenu) {
        this.idMenu = idMenu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="menu_pai")
    public PubMenu getPubMenu() {
        return this.pubMenu;
    }
    
    public void setPubMenu(PubMenu pubMenu) {
        this.pubMenu = pubMenu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sistema", nullable=false)
    public PubSistema getPubSistema() {
        return this.pubSistema;
    }
    
    public void setPubSistema(PubSistema pubSistema) {
        this.pubSistema = pubSistema;
    }

    
    @Column(name="menu", nullable=false, length=25)
    public String getMenu() {
        return this.menu;
    }
    
    public void setMenu(String menu) {
        this.menu = menu;
    }

    
    @Column(name="descricao", nullable=false, length=300)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="caminho", length=150)
    public String getCaminho() {
        return this.caminho;
    }
    
    public void setCaminho(String caminho) {
        this.caminho = caminho;
    }

    
    @Column(name="icone", length=100)
    public String getIcone() {
        return this.icone;
    }
    
    public void setIcone(String icone) {
        this.icone = icone;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubMenu")
    public Set getPubConteudos() {
        return this.pubConteudos;
    }
    
    public void setPubConteudos(Set pubConteudos) {
        this.pubConteudos = pubConteudos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubMenu")
    public Set getPubMenus() {
        return this.pubMenus;
    }
    
    public void setPubMenus(Set pubMenus) {
        this.pubMenus = pubMenus;
    }




}


