package br.com.jvmsoftware.entities;
// Generated 17/Abr/2016 23:30:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PubModeloVeiculo generated by hbm2java
 */
public class PubModeloVeiculo  implements java.io.Serializable {


     private Integer idModeloVeiculo;
     private PubMarcaVeiculo pubMarcaVeiculo;
     private String modeloVeiculo;
     private Set<CadVeiculos> cadVeiculoses = new HashSet<CadVeiculos>(0);

    public PubModeloVeiculo() {
    }

	
    public PubModeloVeiculo(PubMarcaVeiculo pubMarcaVeiculo, String modeloVeiculo) {
        this.pubMarcaVeiculo = pubMarcaVeiculo;
        this.modeloVeiculo = modeloVeiculo;
    }
    public PubModeloVeiculo(PubMarcaVeiculo pubMarcaVeiculo, String modeloVeiculo, Set<CadVeiculos> cadVeiculoses) {
       this.pubMarcaVeiculo = pubMarcaVeiculo;
       this.modeloVeiculo = modeloVeiculo;
       this.cadVeiculoses = cadVeiculoses;
    }
   
    public Integer getIdModeloVeiculo() {
        return this.idModeloVeiculo;
    }
    
    public void setIdModeloVeiculo(Integer idModeloVeiculo) {
        this.idModeloVeiculo = idModeloVeiculo;
    }
    public PubMarcaVeiculo getPubMarcaVeiculo() {
        return this.pubMarcaVeiculo;
    }
    
    public void setPubMarcaVeiculo(PubMarcaVeiculo pubMarcaVeiculo) {
        this.pubMarcaVeiculo = pubMarcaVeiculo;
    }
    public String getModeloVeiculo() {
        return this.modeloVeiculo;
    }
    
    public void setModeloVeiculo(String modeloVeiculo) {
        this.modeloVeiculo = modeloVeiculo;
    }
    public Set<CadVeiculos> getCadVeiculoses() {
        return this.cadVeiculoses;
    }
    
    public void setCadVeiculoses(Set<CadVeiculos> cadVeiculoses) {
        this.cadVeiculoses = cadVeiculoses;
    }




}


