package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PubPosicao generated by hbm2java
 */
@Entity
@Table(name="pub_posicao"
    ,catalog="jvmdsoftware"
)
public class PubPosicao  implements java.io.Serializable {


     private Integer idPosicao;
     private String posicao;
     private String descricao;
     private Set pubConteudos = new HashSet(0);

    public PubPosicao() {
    }

	
    public PubPosicao(String posicao, String descricao) {
        this.posicao = posicao;
        this.descricao = descricao;
    }
    public PubPosicao(String posicao, String descricao, Set pubConteudos) {
       this.posicao = posicao;
       this.descricao = descricao;
       this.pubConteudos = pubConteudos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_posicao", unique=true, nullable=false)
    public Integer getIdPosicao() {
        return this.idPosicao;
    }
    
    public void setIdPosicao(Integer idPosicao) {
        this.idPosicao = idPosicao;
    }

    
    @Column(name="posicao", nullable=false, length=20)
    public String getPosicao() {
        return this.posicao;
    }
    
    public void setPosicao(String posicao) {
        this.posicao = posicao;
    }

    
    @Column(name="descricao", nullable=false, length=200)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubPosicao")
    public Set getPubConteudos() {
        return this.pubConteudos;
    }
    
    public void setPubConteudos(Set pubConteudos) {
        this.pubConteudos = pubConteudos;
    }




}


