package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PubSistema generated by hbm2java
 */
@Entity
@Table(name="pub_sistema"
    ,catalog="jvmdsoftware"
)
public class PubSistema  implements java.io.Serializable {


     private Integer idSistema;
     private String nomeSistema;
     private String descricaoSistema;
     private String imagemSistema;
     private boolean ativo;
     private boolean defaultCadastro;
     private Set pubMenus = new HashSet(0);
     private Set pubFuncionalidades = new HashSet(0);
     private Set supSolicitacaos = new HashSet(0);
     private Set wflWorkflows = new HashSet(0);
     private Set wflSituacaos = new HashSet(0);
     private Set ctrLogs = new HashSet(0);
     private Set acsEmpresaSistemas = new HashSet(0);
     private Set acsUsuarioSistemas = new HashSet(0);

    public PubSistema() {
    }

	
    public PubSistema(String nomeSistema, String descricaoSistema, boolean ativo, boolean defaultCadastro) {
        this.nomeSistema = nomeSistema;
        this.descricaoSistema = descricaoSistema;
        this.ativo = ativo;
        this.defaultCadastro = defaultCadastro;
    }
    public PubSistema(String nomeSistema, String descricaoSistema, String imagemSistema, boolean ativo, boolean defaultCadastro, Set pubMenus, Set pubFuncionalidades, Set supSolicitacaos, Set wflWorkflows, Set wflSituacaos, Set ctrLogs, Set acsEmpresaSistemas, Set acsUsuarioSistemas) {
       this.nomeSistema = nomeSistema;
       this.descricaoSistema = descricaoSistema;
       this.imagemSistema = imagemSistema;
       this.ativo = ativo;
       this.defaultCadastro = defaultCadastro;
       this.pubMenus = pubMenus;
       this.pubFuncionalidades = pubFuncionalidades;
       this.supSolicitacaos = supSolicitacaos;
       this.wflWorkflows = wflWorkflows;
       this.wflSituacaos = wflSituacaos;
       this.ctrLogs = ctrLogs;
       this.acsEmpresaSistemas = acsEmpresaSistemas;
       this.acsUsuarioSistemas = acsUsuarioSistemas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_sistema", unique=true, nullable=false)
    public Integer getIdSistema() {
        return this.idSistema;
    }
    
    public void setIdSistema(Integer idSistema) {
        this.idSistema = idSistema;
    }

    
    @Column(name="nome_sistema", nullable=false, length=20)
    public String getNomeSistema() {
        return this.nomeSistema;
    }
    
    public void setNomeSistema(String nomeSistema) {
        this.nomeSistema = nomeSistema;
    }

    
    @Column(name="descricao_sistema", nullable=false, length=500)
    public String getDescricaoSistema() {
        return this.descricaoSistema;
    }
    
    public void setDescricaoSistema(String descricaoSistema) {
        this.descricaoSistema = descricaoSistema;
    }

    
    @Column(name="imagem_sistema", length=200)
    public String getImagemSistema() {
        return this.imagemSistema;
    }
    
    public void setImagemSistema(String imagemSistema) {
        this.imagemSistema = imagemSistema;
    }

    
    @Column(name="ativo", nullable=false)
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }

    
    @Column(name="defaultCadastro", nullable=false)
    public boolean getDefaultCadastro() {
        return this.defaultCadastro;
    }
    
    public void setDefaultCadastro(boolean defaultCadastro) {
        this.defaultCadastro = defaultCadastro;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubSistema")
    public Set getPubMenus() {
        return this.pubMenus;
    }
    
    public void setPubMenus(Set pubMenus) {
        this.pubMenus = pubMenus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubSistema")
    public Set getPubFuncionalidades() {
        return this.pubFuncionalidades;
    }
    
    public void setPubFuncionalidades(Set pubFuncionalidades) {
        this.pubFuncionalidades = pubFuncionalidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubSistema")
    public Set getSupSolicitacaos() {
        return this.supSolicitacaos;
    }
    
    public void setSupSolicitacaos(Set supSolicitacaos) {
        this.supSolicitacaos = supSolicitacaos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubSistema")
    public Set getWflWorkflows() {
        return this.wflWorkflows;
    }
    
    public void setWflWorkflows(Set wflWorkflows) {
        this.wflWorkflows = wflWorkflows;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubSistema")
    public Set getWflSituacaos() {
        return this.wflSituacaos;
    }
    
    public void setWflSituacaos(Set wflSituacaos) {
        this.wflSituacaos = wflSituacaos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubSistema")
    public Set getCtrLogs() {
        return this.ctrLogs;
    }
    
    public void setCtrLogs(Set ctrLogs) {
        this.ctrLogs = ctrLogs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubSistema")
    public Set getAcsEmpresaSistemas() {
        return this.acsEmpresaSistemas;
    }
    
    public void setAcsEmpresaSistemas(Set acsEmpresaSistemas) {
        this.acsEmpresaSistemas = acsEmpresaSistemas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubSistema")
    public Set getAcsUsuarioSistemas() {
        return this.acsUsuarioSistemas;
    }
    
    public void setAcsUsuarioSistemas(Set acsUsuarioSistemas) {
        this.acsUsuarioSistemas = acsUsuarioSistemas;
    }




}


