package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PubTipoEndereco generated by hbm2java
 */
@Entity
@Table(name="pub_tipo_endereco"
    ,catalog="jvmdsoftware"
)
public class PubTipoEndereco  implements java.io.Serializable {


     private Integer id;
     private String codTipoEndereco;
     private String tipoEndereco;
     private Set cadEnderecoses = new HashSet(0);

    public PubTipoEndereco() {
    }

    public PubTipoEndereco(String codTipoEndereco, String tipoEndereco, Set cadEnderecoses) {
       this.codTipoEndereco = codTipoEndereco;
       this.tipoEndereco = tipoEndereco;
       this.cadEnderecoses = cadEnderecoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="cod_tipo_endereco", length=3)
    public String getCodTipoEndereco() {
        return this.codTipoEndereco;
    }
    
    public void setCodTipoEndereco(String codTipoEndereco) {
        this.codTipoEndereco = codTipoEndereco;
    }

    
    @Column(name="tipo_endereco", length=50)
    public String getTipoEndereco() {
        return this.tipoEndereco;
    }
    
    public void setTipoEndereco(String tipoEndereco) {
        this.tipoEndereco = tipoEndereco;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubTipoEndereco")
    public Set getCadEnderecoses() {
        return this.cadEnderecoses;
    }
    
    public void setCadEnderecoses(Set cadEnderecoses) {
        this.cadEnderecoses = cadEnderecoses;
    }




}


