package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PubTipoNegocio generated by hbm2java
 */
@Entity
@Table(name="pub_tipo_negocio"
    ,catalog="jvmdsoftware"
)
public class PubTipoNegocio  implements java.io.Serializable {


     private Integer idTipoNegocio;
     private PubTipoEmpresa pubTipoEmpresa;
     private String tipoNegocio;
     private Set pubConfigEmpresas = new HashSet(0);

    public PubTipoNegocio() {
    }

	
    public PubTipoNegocio(PubTipoEmpresa pubTipoEmpresa, String tipoNegocio) {
        this.pubTipoEmpresa = pubTipoEmpresa;
        this.tipoNegocio = tipoNegocio;
    }
    public PubTipoNegocio(PubTipoEmpresa pubTipoEmpresa, String tipoNegocio, Set pubConfigEmpresas) {
       this.pubTipoEmpresa = pubTipoEmpresa;
       this.tipoNegocio = tipoNegocio;
       this.pubConfigEmpresas = pubConfigEmpresas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_negocio", unique=true, nullable=false)
    public Integer getIdTipoNegocio() {
        return this.idTipoNegocio;
    }
    
    public void setIdTipoNegocio(Integer idTipoNegocio) {
        this.idTipoNegocio = idTipoNegocio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tipo_empresa", nullable=false)
    public PubTipoEmpresa getPubTipoEmpresa() {
        return this.pubTipoEmpresa;
    }
    
    public void setPubTipoEmpresa(PubTipoEmpresa pubTipoEmpresa) {
        this.pubTipoEmpresa = pubTipoEmpresa;
    }

    
    @Column(name="tipo_negocio", nullable=false, length=100)
    public String getTipoNegocio() {
        return this.tipoNegocio;
    }
    
    public void setTipoNegocio(String tipoNegocio) {
        this.tipoNegocio = tipoNegocio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubTipoNegocio")
    public Set getPubConfigEmpresas() {
        return this.pubConfigEmpresas;
    }
    
    public void setPubConfigEmpresas(Set pubConfigEmpresas) {
        this.pubConfigEmpresas = pubConfigEmpresas;
    }




}


