package br.com.jvmsoftware.entities;
// Generated 27/Mar/2016 8:26:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PubTipoEndereco generated by hbm2java
 */
public class PubTipoEndereco  implements java.io.Serializable {


     private Integer id;
     private String codTipoEndereco;
     private String tipoEndereco;
     private Set<CadEnderecos> cadEnderecoses = new HashSet<CadEnderecos>(0);

    public PubTipoEndereco() {
    }

    public PubTipoEndereco(String codTipoEndereco, String tipoEndereco, Set<CadEnderecos> cadEnderecoses) {
       this.codTipoEndereco = codTipoEndereco;
       this.tipoEndereco = tipoEndereco;
       this.cadEnderecoses = cadEnderecoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodTipoEndereco() {
        return this.codTipoEndereco;
    }
    
    public void setCodTipoEndereco(String codTipoEndereco) {
        this.codTipoEndereco = codTipoEndereco;
    }
    public String getTipoEndereco() {
        return this.tipoEndereco;
    }
    
    public void setTipoEndereco(String tipoEndereco) {
        this.tipoEndereco = tipoEndereco;
    }
    public Set<CadEnderecos> getCadEnderecoses() {
        return this.cadEnderecoses;
    }
    
    public void setCadEnderecoses(Set<CadEnderecos> cadEnderecoses) {
        this.cadEnderecoses = cadEnderecoses;
    }




}


