package br.com.jvmsoftware.entities;
// Generated 9/Abr/2016 18:34:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PubTipoImovel generated by hbm2java
 */
public class PubTipoImovel  implements java.io.Serializable {


     private Integer idTipoImovel;
     private String tipoImovel;
     private Set<CadImoveis> cadImoveises = new HashSet<CadImoveis>(0);

    public PubTipoImovel() {
    }

	
    public PubTipoImovel(String tipoImovel) {
        this.tipoImovel = tipoImovel;
    }
    public PubTipoImovel(String tipoImovel, Set<CadImoveis> cadImoveises) {
       this.tipoImovel = tipoImovel;
       this.cadImoveises = cadImoveises;
    }
   
    public Integer getIdTipoImovel() {
        return this.idTipoImovel;
    }
    
    public void setIdTipoImovel(Integer idTipoImovel) {
        this.idTipoImovel = idTipoImovel;
    }
    public String getTipoImovel() {
        return this.tipoImovel;
    }
    
    public void setTipoImovel(String tipoImovel) {
        this.tipoImovel = tipoImovel;
    }
    public Set<CadImoveis> getCadImoveises() {
        return this.cadImoveises;
    }
    
    public void setCadImoveises(Set<CadImoveis> cadImoveises) {
        this.cadImoveises = cadImoveises;
    }




}


