package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PubTipoVeiculo generated by hbm2java
 */
@Entity
@Table(name="pub_tipo_veiculo"
    ,catalog="jvmdsoftware"
)
public class PubTipoVeiculo  implements java.io.Serializable {


     private Integer idTipoVeiculo;
     private String tipoVeiculo;
     private Set cadVeiculoses = new HashSet(0);
     private Set pubMarcaVeiculos = new HashSet(0);

    public PubTipoVeiculo() {
    }

	
    public PubTipoVeiculo(String tipoVeiculo) {
        this.tipoVeiculo = tipoVeiculo;
    }
    public PubTipoVeiculo(String tipoVeiculo, Set cadVeiculoses, Set pubMarcaVeiculos) {
       this.tipoVeiculo = tipoVeiculo;
       this.cadVeiculoses = cadVeiculoses;
       this.pubMarcaVeiculos = pubMarcaVeiculos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_veiculo", unique=true, nullable=false)
    public Integer getIdTipoVeiculo() {
        return this.idTipoVeiculo;
    }
    
    public void setIdTipoVeiculo(Integer idTipoVeiculo) {
        this.idTipoVeiculo = idTipoVeiculo;
    }

    
    @Column(name="tipo_veiculo", nullable=false, length=50)
    public String getTipoVeiculo() {
        return this.tipoVeiculo;
    }
    
    public void setTipoVeiculo(String tipoVeiculo) {
        this.tipoVeiculo = tipoVeiculo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubTipoVeiculo")
    public Set getCadVeiculoses() {
        return this.cadVeiculoses;
    }
    
    public void setCadVeiculoses(Set cadVeiculoses) {
        this.cadVeiculoses = cadVeiculoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubTipoVeiculo")
    public Set getPubMarcaVeiculos() {
        return this.pubMarcaVeiculos;
    }
    
    public void setPubMarcaVeiculos(Set pubMarcaVeiculos) {
        this.pubMarcaVeiculos = pubMarcaVeiculos;
    }




}


