package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PubTipoEquipamento generated by hbm2java
 */
@Entity
@Table(name="pub_tipo_equipamento"
    ,catalog="jvmdsoftware"
)
public class PubTipoEquipamento  implements java.io.Serializable {


     private Integer idTipoEquipamento;
     private String tipoEquipamento;
     private Set cadEquipamentoses = new HashSet(0);

    public PubTipoEquipamento() {
    }

	
    public PubTipoEquipamento(String tipoEquipamento) {
        this.tipoEquipamento = tipoEquipamento;
    }
    public PubTipoEquipamento(String tipoEquipamento, Set cadEquipamentoses) {
       this.tipoEquipamento = tipoEquipamento;
       this.cadEquipamentoses = cadEquipamentoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_equipamento", unique=true, nullable=false)
    public Integer getIdTipoEquipamento() {
        return this.idTipoEquipamento;
    }
    
    public void setIdTipoEquipamento(Integer idTipoEquipamento) {
        this.idTipoEquipamento = idTipoEquipamento;
    }

    
    @Column(name="tipo_equipamento", nullable=false, length=50)
    public String getTipoEquipamento() {
        return this.tipoEquipamento;
    }
    
    public void setTipoEquipamento(String tipoEquipamento) {
        this.tipoEquipamento = tipoEquipamento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubTipoEquipamento")
    public Set getCadEquipamentoses() {
        return this.cadEquipamentoses;
    }
    
    public void setCadEquipamentoses(Set cadEquipamentoses) {
        this.cadEquipamentoses = cadEquipamentoses;
    }




}


