package br.com.jvmsoftware.entities;
// Generated 3/Abr/2016 2:22:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PubTipoEquipamento generated by hbm2java
 */
public class PubTipoEquipamento  implements java.io.Serializable {


     private Integer idTipoEquipamento;
     private String tipoEquipamento;
     private Set<CadEquipamentos> cadEquipamentoses = new HashSet<CadEquipamentos>(0);

    public PubTipoEquipamento() {
    }

	
    public PubTipoEquipamento(String tipoEquipamento) {
        this.tipoEquipamento = tipoEquipamento;
    }
    public PubTipoEquipamento(String tipoEquipamento, Set<CadEquipamentos> cadEquipamentoses) {
       this.tipoEquipamento = tipoEquipamento;
       this.cadEquipamentoses = cadEquipamentoses;
    }
   
    public Integer getIdTipoEquipamento() {
        return this.idTipoEquipamento;
    }
    
    public void setIdTipoEquipamento(Integer idTipoEquipamento) {
        this.idTipoEquipamento = idTipoEquipamento;
    }
    public String getTipoEquipamento() {
        return this.tipoEquipamento;
    }
    
    public void setTipoEquipamento(String tipoEquipamento) {
        this.tipoEquipamento = tipoEquipamento;
    }
    public Set<CadEquipamentos> getCadEquipamentoses() {
        return this.cadEquipamentoses;
    }
    
    public void setCadEquipamentoses(Set<CadEquipamentos> cadEquipamentoses) {
        this.cadEquipamentoses = cadEquipamentoses;
    }




}


