package br.com.jvmsoftware.entities;
// Generated 3/Abr/2016 2:22:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PubTipoEmpresa generated by hbm2java
 */
public class PubTipoEmpresa  implements java.io.Serializable {


     private Integer idTipoEmpresa;
     private String tipoEmpresa;
     private Set<PubTipoNegocio> pubTipoNegocios = new HashSet<PubTipoNegocio>(0);
     private Set<PubConfigEmpresa> pubConfigEmpresas = new HashSet<PubConfigEmpresa>(0);

    public PubTipoEmpresa() {
    }

	
    public PubTipoEmpresa(String tipoEmpresa) {
        this.tipoEmpresa = tipoEmpresa;
    }
    public PubTipoEmpresa(String tipoEmpresa, Set<PubTipoNegocio> pubTipoNegocios, Set<PubConfigEmpresa> pubConfigEmpresas) {
       this.tipoEmpresa = tipoEmpresa;
       this.pubTipoNegocios = pubTipoNegocios;
       this.pubConfigEmpresas = pubConfigEmpresas;
    }
   
    public Integer getIdTipoEmpresa() {
        return this.idTipoEmpresa;
    }
    
    public void setIdTipoEmpresa(Integer idTipoEmpresa) {
        this.idTipoEmpresa = idTipoEmpresa;
    }
    public String getTipoEmpresa() {
        return this.tipoEmpresa;
    }
    
    public void setTipoEmpresa(String tipoEmpresa) {
        this.tipoEmpresa = tipoEmpresa;
    }
    public Set<PubTipoNegocio> getPubTipoNegocios() {
        return this.pubTipoNegocios;
    }
    
    public void setPubTipoNegocios(Set<PubTipoNegocio> pubTipoNegocios) {
        this.pubTipoNegocios = pubTipoNegocios;
    }
    public Set<PubConfigEmpresa> getPubConfigEmpresas() {
        return this.pubConfigEmpresas;
    }
    
    public void setPubConfigEmpresas(Set<PubConfigEmpresa> pubConfigEmpresas) {
        this.pubConfigEmpresas = pubConfigEmpresas;
    }




}


