package br.com.jvmsoftware.entities;
// Generated 4/Ago/2015 22:25:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PubTipoEmpresa generated by hbm2java
 */
public class PubTipoEmpresa  implements java.io.Serializable {


     private Integer idTipoEmpresa;
     private String tipoEmpresa;
     private Set<PubTipoNegocio> pubTipoNegocios = new HashSet<PubTipoNegocio>(0);

    public PubTipoEmpresa() {
    }

	
    public PubTipoEmpresa(String tipoEmpresa) {
        this.tipoEmpresa = tipoEmpresa;
    }
    public PubTipoEmpresa(String tipoEmpresa, Set<PubTipoNegocio> pubTipoNegocios) {
       this.tipoEmpresa = tipoEmpresa;
       this.pubTipoNegocios = pubTipoNegocios;
    }
   
    public Integer getIdTipoEmpresa() {
        return this.idTipoEmpresa;
    }
    
    public void setIdTipoEmpresa(Integer idTipoEmpresa) {
        this.idTipoEmpresa = idTipoEmpresa;
    }
    public String getTipoEmpresa() {
        return this.tipoEmpresa;
    }
    
    public void setTipoEmpresa(String tipoEmpresa) {
        this.tipoEmpresa = tipoEmpresa;
    }
    public Set<PubTipoNegocio> getPubTipoNegocios() {
        return this.pubTipoNegocios;
    }
    
    public void setPubTipoNegocios(Set<PubTipoNegocio> pubTipoNegocios) {
        this.pubTipoNegocios = pubTipoNegocios;
    }




}


