package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PubTipoCadastro generated by hbm2java
 */
@Entity
@Table(name="pub_tipo_cadastro"
    ,catalog="jvmdsoftware"
)
public class PubTipoCadastro  implements java.io.Serializable {


     private Integer idTipoCadastro;
     private String codigoTipoCadastro;
     private String descricaoTipoCadastro;
     private Set cadPessoas = new HashSet(0);
     private Set pubEmpresas = new HashSet(0);

    public PubTipoCadastro() {
    }

	
    public PubTipoCadastro(String codigoTipoCadastro, String descricaoTipoCadastro) {
        this.codigoTipoCadastro = codigoTipoCadastro;
        this.descricaoTipoCadastro = descricaoTipoCadastro;
    }
    public PubTipoCadastro(String codigoTipoCadastro, String descricaoTipoCadastro, Set cadPessoas, Set pubEmpresas) {
       this.codigoTipoCadastro = codigoTipoCadastro;
       this.descricaoTipoCadastro = descricaoTipoCadastro;
       this.cadPessoas = cadPessoas;
       this.pubEmpresas = pubEmpresas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_cadastro", unique=true, nullable=false)
    public Integer getIdTipoCadastro() {
        return this.idTipoCadastro;
    }
    
    public void setIdTipoCadastro(Integer idTipoCadastro) {
        this.idTipoCadastro = idTipoCadastro;
    }

    
    @Column(name="codigo_tipo_cadastro", nullable=false, length=2)
    public String getCodigoTipoCadastro() {
        return this.codigoTipoCadastro;
    }
    
    public void setCodigoTipoCadastro(String codigoTipoCadastro) {
        this.codigoTipoCadastro = codigoTipoCadastro;
    }

    
    @Column(name="descricao_tipo_cadastro", nullable=false, length=100)
    public String getDescricaoTipoCadastro() {
        return this.descricaoTipoCadastro;
    }
    
    public void setDescricaoTipoCadastro(String descricaoTipoCadastro) {
        this.descricaoTipoCadastro = descricaoTipoCadastro;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubTipoCadastro")
    public Set getCadPessoas() {
        return this.cadPessoas;
    }
    
    public void setCadPessoas(Set cadPessoas) {
        this.cadPessoas = cadPessoas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubTipoCadastro")
    public Set getPubEmpresas() {
        return this.pubEmpresas;
    }
    
    public void setPubEmpresas(Set pubEmpresas) {
        this.pubEmpresas = pubEmpresas;
    }




}


