package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PubTipoEmpresa generated by hbm2java
 */
@Entity
@Table(name="pub_tipo_empresa"
    ,catalog="jvmdsoftware"
)
public class PubTipoEmpresa  implements java.io.Serializable {


     private Integer idTipoEmpresa;
     private String tipoEmpresa;
     private Set pubTipoNegocios = new HashSet(0);
     private Set pubConfigEmpresas = new HashSet(0);

    public PubTipoEmpresa() {
    }

	
    public PubTipoEmpresa(String tipoEmpresa) {
        this.tipoEmpresa = tipoEmpresa;
    }
    public PubTipoEmpresa(String tipoEmpresa, Set pubTipoNegocios, Set pubConfigEmpresas) {
       this.tipoEmpresa = tipoEmpresa;
       this.pubTipoNegocios = pubTipoNegocios;
       this.pubConfigEmpresas = pubConfigEmpresas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_empresa", unique=true, nullable=false)
    public Integer getIdTipoEmpresa() {
        return this.idTipoEmpresa;
    }
    
    public void setIdTipoEmpresa(Integer idTipoEmpresa) {
        this.idTipoEmpresa = idTipoEmpresa;
    }

    
    @Column(name="tipo_empresa", nullable=false, length=80)
    public String getTipoEmpresa() {
        return this.tipoEmpresa;
    }
    
    public void setTipoEmpresa(String tipoEmpresa) {
        this.tipoEmpresa = tipoEmpresa;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubTipoEmpresa")
    public Set getPubTipoNegocios() {
        return this.pubTipoNegocios;
    }
    
    public void setPubTipoNegocios(Set pubTipoNegocios) {
        this.pubTipoNegocios = pubTipoNegocios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubTipoEmpresa")
    public Set getPubConfigEmpresas() {
        return this.pubConfigEmpresas;
    }
    
    public void setPubConfigEmpresas(Set pubConfigEmpresas) {
        this.pubConfigEmpresas = pubConfigEmpresas;
    }




}


