package br.com.jvmsoftware.entities;
// Generated 4/Ago/2015 22:25:45 by Hibernate Tools 4.3.1



/**
 * PubTipoNegocio generated by hbm2java
 */
public class PubTipoNegocio  implements java.io.Serializable {


     private Integer idTipoNegocio;
     private PubTipoEmpresa pubTipoEmpresa;
     private String tipoNegocio;

    public PubTipoNegocio() {
    }

    public PubTipoNegocio(PubTipoEmpresa pubTipoEmpresa, String tipoNegocio) {
       this.pubTipoEmpresa = pubTipoEmpresa;
       this.tipoNegocio = tipoNegocio;
    }
   
    public Integer getIdTipoNegocio() {
        return this.idTipoNegocio;
    }
    
    public void setIdTipoNegocio(Integer idTipoNegocio) {
        this.idTipoNegocio = idTipoNegocio;
    }
    public PubTipoEmpresa getPubTipoEmpresa() {
        return this.pubTipoEmpresa;
    }
    
    public void setPubTipoEmpresa(PubTipoEmpresa pubTipoEmpresa) {
        this.pubTipoEmpresa = pubTipoEmpresa;
    }
    public String getTipoNegocio() {
        return this.tipoNegocio;
    }
    
    public void setTipoNegocio(String tipoNegocio) {
        this.tipoNegocio = tipoNegocio;
    }




}


