package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PubUsuario generated by hbm2java
 */
@Entity
@Table(name="pub_usuario"
    ,catalog="jvmdsoftware"
)
public class PubUsuario  implements java.io.Serializable {


     private Integer idUsuario;
     private PubEmpresa pubEmpresa;
     private PubEstado pubEstado;
     private PubMunicipio pubMunicipio;
     private String cpfUsuario;
     private String nomeUsuario;
     private String email;
     private String senha;
     private Date dataNascimento;
     private Date dataCadastro;
     private Date dataVerificacao;
     private String codigoVerificacao;
     private boolean ativo;
     private Date dataRessetSenha;
     private Date dataValidacaoResset;
     private String endereco;
     private Double numero;
     private String bairro;
     private String complemento;
     private Double cep;
     private Double telefone;
     private boolean master;
     private Set acsAcessoUsuarioses = new HashSet(0);
     private Set acsUsuarioFuncionalidades = new HashSet(0);
     private Set ctrLogs = new HashSet(0);
     private Set wflWorkflowEventos = new HashSet(0);
     private Set wflWorkflows = new HashSet(0);
     private Set supProjetos = new HashSet(0);
     private Set supSolicitacaos = new HashSet(0);
     private Set comCompraOrdems = new HashSet(0);
     private Set servOrdemServicos = new HashSet(0);
     private Set acsUsuarioSistemas = new HashSet(0);

    public PubUsuario() {
    }

	
    public PubUsuario(String nomeUsuario, String email, String senha, boolean ativo, boolean master) {
        this.nomeUsuario = nomeUsuario;
        this.email = email;
        this.senha = senha;
        this.ativo = ativo;
        this.master = master;
    }
    public PubUsuario(PubEmpresa pubEmpresa, PubEstado pubEstado, PubMunicipio pubMunicipio, String cpfUsuario, String nomeUsuario, String email, String senha, Date dataNascimento, Date dataCadastro, Date dataVerificacao, String codigoVerificacao, boolean ativo, Date dataRessetSenha, Date dataValidacaoResset, String endereco, Double numero, String bairro, String complemento, Double cep, Double telefone, boolean master, Set acsAcessoUsuarioses, Set acsUsuarioFuncionalidades, Set ctrLogs, Set wflWorkflowEventos, Set wflWorkflows, Set supProjetos, Set supSolicitacaos, Set comCompraOrdems, Set servOrdemServicos, Set acsUsuarioSistemas) {
       this.pubEmpresa = pubEmpresa;
       this.pubEstado = pubEstado;
       this.pubMunicipio = pubMunicipio;
       this.cpfUsuario = cpfUsuario;
       this.nomeUsuario = nomeUsuario;
       this.email = email;
       this.senha = senha;
       this.dataNascimento = dataNascimento;
       this.dataCadastro = dataCadastro;
       this.dataVerificacao = dataVerificacao;
       this.codigoVerificacao = codigoVerificacao;
       this.ativo = ativo;
       this.dataRessetSenha = dataRessetSenha;
       this.dataValidacaoResset = dataValidacaoResset;
       this.endereco = endereco;
       this.numero = numero;
       this.bairro = bairro;
       this.complemento = complemento;
       this.cep = cep;
       this.telefone = telefone;
       this.master = master;
       this.acsAcessoUsuarioses = acsAcessoUsuarioses;
       this.acsUsuarioFuncionalidades = acsUsuarioFuncionalidades;
       this.ctrLogs = ctrLogs;
       this.wflWorkflowEventos = wflWorkflowEventos;
       this.wflWorkflows = wflWorkflows;
       this.supProjetos = supProjetos;
       this.supSolicitacaos = supSolicitacaos;
       this.comCompraOrdems = comCompraOrdems;
       this.servOrdemServicos = servOrdemServicos;
       this.acsUsuarioSistemas = acsUsuarioSistemas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_usuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa")
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="estado")
    public PubEstado getPubEstado() {
        return this.pubEstado;
    }
    
    public void setPubEstado(PubEstado pubEstado) {
        this.pubEstado = pubEstado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cidade")
    public PubMunicipio getPubMunicipio() {
        return this.pubMunicipio;
    }
    
    public void setPubMunicipio(PubMunicipio pubMunicipio) {
        this.pubMunicipio = pubMunicipio;
    }

    
    @Column(name="cpf_usuario", length=11)
    public String getCpfUsuario() {
        return this.cpfUsuario;
    }
    
    public void setCpfUsuario(String cpfUsuario) {
        this.cpfUsuario = cpfUsuario;
    }

    
    @Column(name="nome_usuario", nullable=false, length=100)
    public String getNomeUsuario() {
        return this.nomeUsuario;
    }
    
    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="senha", nullable=false)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_nascimento", length=10)
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_cadastro", length=19)
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_verificacao", length=19)
    public Date getDataVerificacao() {
        return this.dataVerificacao;
    }
    
    public void setDataVerificacao(Date dataVerificacao) {
        this.dataVerificacao = dataVerificacao;
    }

    
    @Column(name="codigo_verificacao", length=8)
    public String getCodigoVerificacao() {
        return this.codigoVerificacao;
    }
    
    public void setCodigoVerificacao(String codigoVerificacao) {
        this.codigoVerificacao = codigoVerificacao;
    }

    
    @Column(name="ativo", nullable=false)
    public boolean isAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_resset_senha", length=19)
    public Date getDataRessetSenha() {
        return this.dataRessetSenha;
    }
    
    public void setDataRessetSenha(Date dataRessetSenha) {
        this.dataRessetSenha = dataRessetSenha;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_validacao_resset", length=19)
    public Date getDataValidacaoResset() {
        return this.dataValidacaoResset;
    }
    
    public void setDataValidacaoResset(Date dataValidacaoResset) {
        this.dataValidacaoResset = dataValidacaoResset;
    }

    
    @Column(name="endereco", length=100)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="numero", precision=22, scale=0)
    public Double getNumero() {
        return this.numero;
    }
    
    public void setNumero(Double numero) {
        this.numero = numero;
    }

    
    @Column(name="bairro", length=50)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="complemento", length=150)
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    
    @Column(name="cep", precision=22, scale=0)
    public Double getCep() {
        return this.cep;
    }
    
    public void setCep(Double cep) {
        this.cep = cep;
    }

    
    @Column(name="telefone", precision=22, scale=0)
    public Double getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(Double telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="master", nullable=false)
    public boolean isMaster() {
        return this.master;
    }
    
    public void setMaster(boolean master) {
        this.master = master;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubUsuario")
    public Set getAcsAcessoUsuarioses() {
        return this.acsAcessoUsuarioses;
    }
    
    public void setAcsAcessoUsuarioses(Set acsAcessoUsuarioses) {
        this.acsAcessoUsuarioses = acsAcessoUsuarioses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubUsuario")
    public Set getAcsUsuarioFuncionalidades() {
        return this.acsUsuarioFuncionalidades;
    }
    
    public void setAcsUsuarioFuncionalidades(Set acsUsuarioFuncionalidades) {
        this.acsUsuarioFuncionalidades = acsUsuarioFuncionalidades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubUsuario")
    public Set getCtrLogs() {
        return this.ctrLogs;
    }
    
    public void setCtrLogs(Set ctrLogs) {
        this.ctrLogs = ctrLogs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubUsuario")
    public Set getWflWorkflowEventos() {
        return this.wflWorkflowEventos;
    }
    
    public void setWflWorkflowEventos(Set wflWorkflowEventos) {
        this.wflWorkflowEventos = wflWorkflowEventos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubUsuario")
    public Set getWflWorkflows() {
        return this.wflWorkflows;
    }
    
    public void setWflWorkflows(Set wflWorkflows) {
        this.wflWorkflows = wflWorkflows;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubUsuario")
    public Set getSupProjetos() {
        return this.supProjetos;
    }
    
    public void setSupProjetos(Set supProjetos) {
        this.supProjetos = supProjetos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubUsuario")
    public Set getSupSolicitacaos() {
        return this.supSolicitacaos;
    }
    
    public void setSupSolicitacaos(Set supSolicitacaos) {
        this.supSolicitacaos = supSolicitacaos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubUsuario")
    public Set getComCompraOrdems() {
        return this.comCompraOrdems;
    }
    
    public void setComCompraOrdems(Set comCompraOrdems) {
        this.comCompraOrdems = comCompraOrdems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubUsuario")
    public Set getServOrdemServicos() {
        return this.servOrdemServicos;
    }
    
    public void setServOrdemServicos(Set servOrdemServicos) {
        this.servOrdemServicos = servOrdemServicos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pubUsuario")
    public Set getAcsUsuarioSistemas() {
        return this.acsUsuarioSistemas;
    }
    
    public void setAcsUsuarioSistemas(Set acsUsuarioSistemas) {
        this.acsUsuarioSistemas = acsUsuarioSistemas;
    }




}


