package br.com.jvmsoftware.entities;
// Generated 4/Ago/2015 22:25:45 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PubUsuario generated by hbm2java
 */
public class PubUsuario  implements java.io.Serializable {


     private Integer idUsuario;
     private PubEmpresa pubEmpresa;
     private PubEstado pubEstado;
     private PubMunicipio pubMunicipio;
     private Float cpfUsuario;
     private String nomeUsuario;
     private String email;
     private String senha;
     private Date dataNascimento;
     private Date dataCadastro;
     private Date dataVerificacao;
     private String codigoVerificacao;
     private boolean ativo;
     private Date dataRessetSenha;
     private Date dataValidacaoResset;
     private String endereco;
     private Float numero;
     private String bairro;
     private String complemento;
     private Float cep;
     private Float telefone;
     private Boolean master;
     private Set<AcsAcessoUsuarios> acsAcessoUsuarioses = new HashSet<AcsAcessoUsuarios>(0);
     private Set<CtrLog> ctrLogs = new HashSet<CtrLog>(0);
     private Set<WflWorkflowEvento> wflWorkflowEventos = new HashSet<WflWorkflowEvento>(0);
     private Set<WflWorkflow> wflWorkflows = new HashSet<WflWorkflow>(0);
     private Set<SupProjeto> supProjetos = new HashSet<SupProjeto>(0);
     private Set<SupSolicitacao> supSolicitacaos = new HashSet<SupSolicitacao>(0);
     private Set<AcsUsuarioSistema> acsUsuarioSistemas = new HashSet<AcsUsuarioSistema>(0);

    public PubUsuario() {
    }

	
    public PubUsuario(String nomeUsuario, String email, String senha, boolean ativo) {
        this.nomeUsuario = nomeUsuario;
        this.email = email;
        this.senha = senha;
        this.ativo = ativo;
    }
    public PubUsuario(PubEmpresa pubEmpresa, PubEstado pubEstado, PubMunicipio pubMunicipio, Float cpfUsuario, String nomeUsuario, String email, String senha, Date dataNascimento, Date dataCadastro, Date dataVerificacao, String codigoVerificacao, boolean ativo, Date dataRessetSenha, Date dataValidacaoResset, String endereco, Float numero, String bairro, String complemento, Float cep, Float telefone, Boolean master, Set<AcsAcessoUsuarios> acsAcessoUsuarioses, Set<CtrLog> ctrLogs, Set<WflWorkflowEvento> wflWorkflowEventos, Set<WflWorkflow> wflWorkflows, Set<SupProjeto> supProjetos, Set<SupSolicitacao> supSolicitacaos, Set<AcsUsuarioSistema> acsUsuarioSistemas) {
       this.pubEmpresa = pubEmpresa;
       this.pubEstado = pubEstado;
       this.pubMunicipio = pubMunicipio;
       this.cpfUsuario = cpfUsuario;
       this.nomeUsuario = nomeUsuario;
       this.email = email;
       this.senha = senha;
       this.dataNascimento = dataNascimento;
       this.dataCadastro = dataCadastro;
       this.dataVerificacao = dataVerificacao;
       this.codigoVerificacao = codigoVerificacao;
       this.ativo = ativo;
       this.dataRessetSenha = dataRessetSenha;
       this.dataValidacaoResset = dataValidacaoResset;
       this.endereco = endereco;
       this.numero = numero;
       this.bairro = bairro;
       this.complemento = complemento;
       this.cep = cep;
       this.telefone = telefone;
       this.master = master;
       this.acsAcessoUsuarioses = acsAcessoUsuarioses;
       this.ctrLogs = ctrLogs;
       this.wflWorkflowEventos = wflWorkflowEventos;
       this.wflWorkflows = wflWorkflows;
       this.supProjetos = supProjetos;
       this.supSolicitacaos = supSolicitacaos;
       this.acsUsuarioSistemas = acsUsuarioSistemas;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }
    public PubEstado getPubEstado() {
        return this.pubEstado;
    }
    
    public void setPubEstado(PubEstado pubEstado) {
        this.pubEstado = pubEstado;
    }
    public PubMunicipio getPubMunicipio() {
        return this.pubMunicipio;
    }
    
    public void setPubMunicipio(PubMunicipio pubMunicipio) {
        this.pubMunicipio = pubMunicipio;
    }
    public Float getCpfUsuario() {
        return this.cpfUsuario;
    }
    
    public void setCpfUsuario(Float cpfUsuario) {
        this.cpfUsuario = cpfUsuario;
    }
    public String getNomeUsuario() {
        return this.nomeUsuario;
    }
    
    public void setNomeUsuario(String nomeUsuario) {
        this.nomeUsuario = nomeUsuario;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }
    public Date getDataVerificacao() {
        return this.dataVerificacao;
    }
    
    public void setDataVerificacao(Date dataVerificacao) {
        this.dataVerificacao = dataVerificacao;
    }
    public String getCodigoVerificacao() {
        return this.codigoVerificacao;
    }
    
    public void setCodigoVerificacao(String codigoVerificacao) {
        this.codigoVerificacao = codigoVerificacao;
    }
    public boolean getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(boolean ativo) {
        this.ativo = ativo;
    }
    public Date getDataRessetSenha() {
        return this.dataRessetSenha;
    }
    
    public void setDataRessetSenha(Date dataRessetSenha) {
        this.dataRessetSenha = dataRessetSenha;
    }
    public Date getDataValidacaoResset() {
        return this.dataValidacaoResset;
    }
    
    public void setDataValidacaoResset(Date dataValidacaoResset) {
        this.dataValidacaoResset = dataValidacaoResset;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public Float getNumero() {
        return this.numero;
    }
    
    public void setNumero(Float numero) {
        this.numero = numero;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public Float getCep() {
        return this.cep;
    }
    
    public void setCep(Float cep) {
        this.cep = cep;
    }
    public Float getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(Float telefone) {
        this.telefone = telefone;
    }
    public Boolean getMaster() {
        return this.master;
    }
    
    public void setMaster(Boolean master) {
        this.master = master;
    }
    public Set<AcsAcessoUsuarios> getAcsAcessoUsuarioses() {
        return this.acsAcessoUsuarioses;
    }
    
    public void setAcsAcessoUsuarioses(Set<AcsAcessoUsuarios> acsAcessoUsuarioses) {
        this.acsAcessoUsuarioses = acsAcessoUsuarioses;
    }
    public Set<CtrLog> getCtrLogs() {
        return this.ctrLogs;
    }
    
    public void setCtrLogs(Set<CtrLog> ctrLogs) {
        this.ctrLogs = ctrLogs;
    }
    public Set<WflWorkflowEvento> getWflWorkflowEventos() {
        return this.wflWorkflowEventos;
    }
    
    public void setWflWorkflowEventos(Set<WflWorkflowEvento> wflWorkflowEventos) {
        this.wflWorkflowEventos = wflWorkflowEventos;
    }
    public Set<WflWorkflow> getWflWorkflows() {
        return this.wflWorkflows;
    }
    
    public void setWflWorkflows(Set<WflWorkflow> wflWorkflows) {
        this.wflWorkflows = wflWorkflows;
    }
    public Set<SupProjeto> getSupProjetos() {
        return this.supProjetos;
    }
    
    public void setSupProjetos(Set<SupProjeto> supProjetos) {
        this.supProjetos = supProjetos;
    }
    public Set<SupSolicitacao> getSupSolicitacaos() {
        return this.supSolicitacaos;
    }
    
    public void setSupSolicitacaos(Set<SupSolicitacao> supSolicitacaos) {
        this.supSolicitacaos = supSolicitacaos;
    }
    public Set<AcsUsuarioSistema> getAcsUsuarioSistemas() {
        return this.acsUsuarioSistemas;
    }
    
    public void setAcsUsuarioSistemas(Set<AcsUsuarioSistema> acsUsuarioSistemas) {
        this.acsUsuarioSistemas = acsUsuarioSistemas;
    }




}


