package br.com.jvmsoftware.entities;
// Generated 17/Abr/2016 23:30:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ServItemOrdemServico generated by hbm2java
 */
public class ServItemOrdemServico  implements java.io.Serializable {


     private int idItem;
     private CadPessoa cadPessoa;
     private ServOrdemServico servOrdemServico;
     private BigDecimal orcamento;
     private BigDecimal valorFinal;
     private boolean terceirizado;
     private Date prazoEntrega;
     private String observacao;
     private String descricaoServicoSemCadastro;

    public ServItemOrdemServico() {
    }

	
    public ServItemOrdemServico(int idItem, ServOrdemServico servOrdemServico, boolean terceirizado) {
        this.idItem = idItem;
        this.servOrdemServico = servOrdemServico;
        this.terceirizado = terceirizado;
    }
    public ServItemOrdemServico(int idItem, CadPessoa cadPessoa, ServOrdemServico servOrdemServico, BigDecimal orcamento, BigDecimal valorFinal, boolean terceirizado, Date prazoEntrega, String observacao, String descricaoServicoSemCadastro) {
       this.idItem = idItem;
       this.cadPessoa = cadPessoa;
       this.servOrdemServico = servOrdemServico;
       this.orcamento = orcamento;
       this.valorFinal = valorFinal;
       this.terceirizado = terceirizado;
       this.prazoEntrega = prazoEntrega;
       this.observacao = observacao;
       this.descricaoServicoSemCadastro = descricaoServicoSemCadastro;
    }
   
    public int getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(int idItem) {
        this.idItem = idItem;
    }
    public CadPessoa getCadPessoa() {
        return this.cadPessoa;
    }
    
    public void setCadPessoa(CadPessoa cadPessoa) {
        this.cadPessoa = cadPessoa;
    }
    public ServOrdemServico getServOrdemServico() {
        return this.servOrdemServico;
    }
    
    public void setServOrdemServico(ServOrdemServico servOrdemServico) {
        this.servOrdemServico = servOrdemServico;
    }
    public BigDecimal getOrcamento() {
        return this.orcamento;
    }
    
    public void setOrcamento(BigDecimal orcamento) {
        this.orcamento = orcamento;
    }
    public BigDecimal getValorFinal() {
        return this.valorFinal;
    }
    
    public void setValorFinal(BigDecimal valorFinal) {
        this.valorFinal = valorFinal;
    }
    public boolean getTerceirizado() {
        return this.terceirizado;
    }
    
    public void setTerceirizado(boolean terceirizado) {
        this.terceirizado = terceirizado;
    }
    public Date getPrazoEntrega() {
        return this.prazoEntrega;
    }
    
    public void setPrazoEntrega(Date prazoEntrega) {
        this.prazoEntrega = prazoEntrega;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public String getDescricaoServicoSemCadastro() {
        return this.descricaoServicoSemCadastro;
    }
    
    public void setDescricaoServicoSemCadastro(String descricaoServicoSemCadastro) {
        this.descricaoServicoSemCadastro = descricaoServicoSemCadastro;
    }




}


