package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServItemOrdemServico generated by hbm2java
 */
@Entity
@Table(name="serv_item_ordem_servico"
    ,catalog="jvmdsoftware"
)
public class ServItemOrdemServico  implements java.io.Serializable {


     private int idItem;
     private CadPessoa cadPessoa;
     private CadServicos cadServicos;
     private BigDecimal orcamento;
     private BigDecimal valorFinal;
     private boolean terceirizado;
     private Date prazoEntrega;
     private String observacao;
     private String descricaoServicoSemCadastro;

    public ServItemOrdemServico() {
    }

	
    public ServItemOrdemServico(int idItem, CadServicos cadServicos, boolean terceirizado) {
        this.idItem = idItem;
        this.cadServicos = cadServicos;
        this.terceirizado = terceirizado;
    }
    public ServItemOrdemServico(int idItem, CadPessoa cadPessoa, CadServicos cadServicos, BigDecimal orcamento, BigDecimal valorFinal, boolean terceirizado, Date prazoEntrega, String observacao, String descricaoServicoSemCadastro) {
       this.idItem = idItem;
       this.cadPessoa = cadPessoa;
       this.cadServicos = cadServicos;
       this.orcamento = orcamento;
       this.valorFinal = valorFinal;
       this.terceirizado = terceirizado;
       this.prazoEntrega = prazoEntrega;
       this.observacao = observacao;
       this.descricaoServicoSemCadastro = descricaoServicoSemCadastro;
    }
   
     @Id 

    
    @Column(name="id_item", unique=true, nullable=false)
    public int getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(int idItem) {
        this.idItem = idItem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fornecedor")
    public CadPessoa getCadPessoa() {
        return this.cadPessoa;
    }
    
    public void setCadPessoa(CadPessoa cadPessoa) {
        this.cadPessoa = cadPessoa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="servico", nullable=false)
    public CadServicos getCadServicos() {
        return this.cadServicos;
    }
    
    public void setCadServicos(CadServicos cadServicos) {
        this.cadServicos = cadServicos;
    }

    
    @Column(name="orcamento", precision=10)
    public BigDecimal getOrcamento() {
        return this.orcamento;
    }
    
    public void setOrcamento(BigDecimal orcamento) {
        this.orcamento = orcamento;
    }

    
    @Column(name="valor_final", precision=10)
    public BigDecimal getValorFinal() {
        return this.valorFinal;
    }
    
    public void setValorFinal(BigDecimal valorFinal) {
        this.valorFinal = valorFinal;
    }

    
    @Column(name="terceirizado", nullable=false)
    public boolean getTerceirizado() {
        return this.terceirizado;
    }
    
    public void setTerceirizado(boolean terceirizado) {
        this.terceirizado = terceirizado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="prazo_entrega", length=10)
    public Date getPrazoEntrega() {
        return this.prazoEntrega;
    }
    
    public void setPrazoEntrega(Date prazoEntrega) {
        this.prazoEntrega = prazoEntrega;
    }

    
    @Column(name="observacao")
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

    
    @Column(name="descricao_servico_sem_cadastro", length=100)
    public String getDescricaoServicoSemCadastro() {
        return this.descricaoServicoSemCadastro;
    }
    
    public void setDescricaoServicoSemCadastro(String descricaoServicoSemCadastro) {
        this.descricaoServicoSemCadastro = descricaoServicoSemCadastro;
    }




}


