package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SupProjeto generated by hbm2java
 */
@Entity
@Table(name="sup_projeto"
    ,catalog="jvmdsoftware"
)
public class SupProjeto  implements java.io.Serializable {


     private Integer idProjeto;
     private PubEmpresa pubEmpresa;
     private PubUsuario pubUsuario;
     private Date dataHoraCriacao;
     private String titulo;
     private String descricao;
     private String detalhamento;
     private Set supSolicitacaos = new HashSet(0);

    public SupProjeto() {
    }

	
    public SupProjeto(PubEmpresa pubEmpresa, PubUsuario pubUsuario, Date dataHoraCriacao, String titulo, String descricao, String detalhamento) {
        this.pubEmpresa = pubEmpresa;
        this.pubUsuario = pubUsuario;
        this.dataHoraCriacao = dataHoraCriacao;
        this.titulo = titulo;
        this.descricao = descricao;
        this.detalhamento = detalhamento;
    }
    public SupProjeto(PubEmpresa pubEmpresa, PubUsuario pubUsuario, Date dataHoraCriacao, String titulo, String descricao, String detalhamento, Set supSolicitacaos) {
       this.pubEmpresa = pubEmpresa;
       this.pubUsuario = pubUsuario;
       this.dataHoraCriacao = dataHoraCriacao;
       this.titulo = titulo;
       this.descricao = descricao;
       this.detalhamento = detalhamento;
       this.supSolicitacaos = supSolicitacaos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_projeto", unique=true, nullable=false)
    public Integer getIdProjeto() {
        return this.idProjeto;
    }
    
    public void setIdProjeto(Integer idProjeto) {
        this.idProjeto = idProjeto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa_projeto", nullable=false)
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_criacao", nullable=false)
    public PubUsuario getPubUsuario() {
        return this.pubUsuario;
    }
    
    public void setPubUsuario(PubUsuario pubUsuario) {
        this.pubUsuario = pubUsuario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_hora_criacao", nullable=false, length=19)
    public Date getDataHoraCriacao() {
        return this.dataHoraCriacao;
    }
    
    public void setDataHoraCriacao(Date dataHoraCriacao) {
        this.dataHoraCriacao = dataHoraCriacao;
    }

    
    @Column(name="titulo", nullable=false, length=80)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="descricao", nullable=false, length=250)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="detalhamento", nullable=false, length=500)
    public String getDetalhamento() {
        return this.detalhamento;
    }
    
    public void setDetalhamento(String detalhamento) {
        this.detalhamento = detalhamento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="supProjeto")
    public Set getSupSolicitacaos() {
        return this.supSolicitacaos;
    }
    
    public void setSupSolicitacaos(Set supSolicitacaos) {
        this.supSolicitacaos = supSolicitacaos;
    }




}


