package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SupSolicitacao generated by hbm2java
 */
@Entity
@Table(name="sup_solicitacao"
    ,catalog="jvmdsoftware"
)
public class SupSolicitacao  implements java.io.Serializable {


     private Integer idSolicitacao;
     private PubEmpresa pubEmpresa;
     private PubFuncionalidade pubFuncionalidade;
     private PubSistema pubSistema;
     private PubUsuario pubUsuario;
     private SupProjeto supProjeto;
     private WflSeveridade wflSeveridade;
     private WflSituacao wflSituacao;
     private Date dataHoraAbertura;
     private String titulo;
     private String descricao;
     private String detalhamento;

    public SupSolicitacao() {
    }

	
    public SupSolicitacao(PubEmpresa pubEmpresa, PubFuncionalidade pubFuncionalidade, PubSistema pubSistema, PubUsuario pubUsuario, SupProjeto supProjeto, WflSeveridade wflSeveridade, WflSituacao wflSituacao, Date dataHoraAbertura, String titulo, String descricao) {
        this.pubEmpresa = pubEmpresa;
        this.pubFuncionalidade = pubFuncionalidade;
        this.pubSistema = pubSistema;
        this.pubUsuario = pubUsuario;
        this.supProjeto = supProjeto;
        this.wflSeveridade = wflSeveridade;
        this.wflSituacao = wflSituacao;
        this.dataHoraAbertura = dataHoraAbertura;
        this.titulo = titulo;
        this.descricao = descricao;
    }
    public SupSolicitacao(PubEmpresa pubEmpresa, PubFuncionalidade pubFuncionalidade, PubSistema pubSistema, PubUsuario pubUsuario, SupProjeto supProjeto, WflSeveridade wflSeveridade, WflSituacao wflSituacao, Date dataHoraAbertura, String titulo, String descricao, String detalhamento) {
       this.pubEmpresa = pubEmpresa;
       this.pubFuncionalidade = pubFuncionalidade;
       this.pubSistema = pubSistema;
       this.pubUsuario = pubUsuario;
       this.supProjeto = supProjeto;
       this.wflSeveridade = wflSeveridade;
       this.wflSituacao = wflSituacao;
       this.dataHoraAbertura = dataHoraAbertura;
       this.titulo = titulo;
       this.descricao = descricao;
       this.detalhamento = detalhamento;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_solicitacao", unique=true, nullable=false)
    public Integer getIdSolicitacao() {
        return this.idSolicitacao;
    }
    
    public void setIdSolicitacao(Integer idSolicitacao) {
        this.idSolicitacao = idSolicitacao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa_solicitacao", nullable=false)
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionalidade", nullable=false)
    public PubFuncionalidade getPubFuncionalidade() {
        return this.pubFuncionalidade;
    }
    
    public void setPubFuncionalidade(PubFuncionalidade pubFuncionalidade) {
        this.pubFuncionalidade = pubFuncionalidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sistema", nullable=false)
    public PubSistema getPubSistema() {
        return this.pubSistema;
    }
    
    public void setPubSistema(PubSistema pubSistema) {
        this.pubSistema = pubSistema;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_abertura", nullable=false)
    public PubUsuario getPubUsuario() {
        return this.pubUsuario;
    }
    
    public void setPubUsuario(PubUsuario pubUsuario) {
        this.pubUsuario = pubUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="projeto", nullable=false)
    public SupProjeto getSupProjeto() {
        return this.supProjeto;
    }
    
    public void setSupProjeto(SupProjeto supProjeto) {
        this.supProjeto = supProjeto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="severidade", nullable=false)
    public WflSeveridade getWflSeveridade() {
        return this.wflSeveridade;
    }
    
    public void setWflSeveridade(WflSeveridade wflSeveridade) {
        this.wflSeveridade = wflSeveridade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="situacao", nullable=false)
    public WflSituacao getWflSituacao() {
        return this.wflSituacao;
    }
    
    public void setWflSituacao(WflSituacao wflSituacao) {
        this.wflSituacao = wflSituacao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_hora_abertura", nullable=false, length=19)
    public Date getDataHoraAbertura() {
        return this.dataHoraAbertura;
    }
    
    public void setDataHoraAbertura(Date dataHoraAbertura) {
        this.dataHoraAbertura = dataHoraAbertura;
    }

    
    @Column(name="titulo", nullable=false, length=80)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="descricao", nullable=false, length=250)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="detalhamento", length=500)
    public String getDetalhamento() {
        return this.detalhamento;
    }
    
    public void setDetalhamento(String detalhamento) {
        this.detalhamento = detalhamento;
    }




}


