package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * WflSituacao generated by hbm2java
 */
@Entity
@Table(name="wfl_situacao"
    ,catalog="jvmdsoftware"
    , uniqueConstraints = @UniqueConstraint(columnNames={"sistema", "empresa", "prioridade"}) 
)
public class WflSituacao  implements java.io.Serializable {


     private Integer idSituacao;
     private PubEmpresa pubEmpresa;
     private PubSistema pubSistema;
     private String codSituacao;
     private String descricaoSituacao;
     private int prioridade;
     private Set supSolicitacaos = new HashSet(0);
     private Set wflWorkflowEventosForSituacaoAnterior = new HashSet(0);
     private Set wflWorkflowEventosForSituacaoAtual = new HashSet(0);
     private Set wflWorkflows = new HashSet(0);

    public WflSituacao() {
    }

	
    public WflSituacao(PubSistema pubSistema, String codSituacao, String descricaoSituacao, int prioridade) {
        this.pubSistema = pubSistema;
        this.codSituacao = codSituacao;
        this.descricaoSituacao = descricaoSituacao;
        this.prioridade = prioridade;
    }
    public WflSituacao(PubEmpresa pubEmpresa, PubSistema pubSistema, String codSituacao, String descricaoSituacao, int prioridade, Set supSolicitacaos, Set wflWorkflowEventosForSituacaoAnterior, Set wflWorkflowEventosForSituacaoAtual, Set wflWorkflows) {
       this.pubEmpresa = pubEmpresa;
       this.pubSistema = pubSistema;
       this.codSituacao = codSituacao;
       this.descricaoSituacao = descricaoSituacao;
       this.prioridade = prioridade;
       this.supSolicitacaos = supSolicitacaos;
       this.wflWorkflowEventosForSituacaoAnterior = wflWorkflowEventosForSituacaoAnterior;
       this.wflWorkflowEventosForSituacaoAtual = wflWorkflowEventosForSituacaoAtual;
       this.wflWorkflows = wflWorkflows;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_situacao", unique=true, nullable=false)
    public Integer getIdSituacao() {
        return this.idSituacao;
    }
    
    public void setIdSituacao(Integer idSituacao) {
        this.idSituacao = idSituacao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa")
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sistema", nullable=false)
    public PubSistema getPubSistema() {
        return this.pubSistema;
    }
    
    public void setPubSistema(PubSistema pubSistema) {
        this.pubSistema = pubSistema;
    }

    
    @Column(name="cod_situacao", nullable=false, length=5)
    public String getCodSituacao() {
        return this.codSituacao;
    }
    
    public void setCodSituacao(String codSituacao) {
        this.codSituacao = codSituacao;
    }

    
    @Column(name="descricao_situacao", nullable=false, length=100)
    public String getDescricaoSituacao() {
        return this.descricaoSituacao;
    }
    
    public void setDescricaoSituacao(String descricaoSituacao) {
        this.descricaoSituacao = descricaoSituacao;
    }

    
    @Column(name="prioridade", nullable=false)
    public int getPrioridade() {
        return this.prioridade;
    }
    
    public void setPrioridade(int prioridade) {
        this.prioridade = prioridade;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="wflSituacao")
    public Set getSupSolicitacaos() {
        return this.supSolicitacaos;
    }
    
    public void setSupSolicitacaos(Set supSolicitacaos) {
        this.supSolicitacaos = supSolicitacaos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="wflSituacaoBySituacaoAnterior")
    public Set getWflWorkflowEventosForSituacaoAnterior() {
        return this.wflWorkflowEventosForSituacaoAnterior;
    }
    
    public void setWflWorkflowEventosForSituacaoAnterior(Set wflWorkflowEventosForSituacaoAnterior) {
        this.wflWorkflowEventosForSituacaoAnterior = wflWorkflowEventosForSituacaoAnterior;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="wflSituacaoBySituacaoAtual")
    public Set getWflWorkflowEventosForSituacaoAtual() {
        return this.wflWorkflowEventosForSituacaoAtual;
    }
    
    public void setWflWorkflowEventosForSituacaoAtual(Set wflWorkflowEventosForSituacaoAtual) {
        this.wflWorkflowEventosForSituacaoAtual = wflWorkflowEventosForSituacaoAtual;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="wflSituacao")
    public Set getWflWorkflows() {
        return this.wflWorkflows;
    }
    
    public void setWflWorkflows(Set wflWorkflows) {
        this.wflWorkflows = wflWorkflows;
    }




}


