package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * WflSeveridade generated by hbm2java
 */
@Entity
@Table(name="wfl_severidade"
    ,catalog="jvmdsoftware"
    , uniqueConstraints = @UniqueConstraint(columnNames="prioridade") 
)
public class WflSeveridade  implements java.io.Serializable {


     private Integer idSeveridade;
     private String codSeveridade;
     private String descricaoSeveridade;
     private int prioridade;
     private Set wflWorkflows = new HashSet(0);
     private Set wflWorkflowEventosForSeveridadeAtual = new HashSet(0);
     private Set wflWorkflowEventosForSeveridadeAnterior = new HashSet(0);
     private Set supSolicitacaos = new HashSet(0);

    public WflSeveridade() {
    }

	
    public WflSeveridade(String codSeveridade, int prioridade) {
        this.codSeveridade = codSeveridade;
        this.prioridade = prioridade;
    }
    public WflSeveridade(String codSeveridade, String descricaoSeveridade, int prioridade, Set wflWorkflows, Set wflWorkflowEventosForSeveridadeAtual, Set wflWorkflowEventosForSeveridadeAnterior, Set supSolicitacaos) {
       this.codSeveridade = codSeveridade;
       this.descricaoSeveridade = descricaoSeveridade;
       this.prioridade = prioridade;
       this.wflWorkflows = wflWorkflows;
       this.wflWorkflowEventosForSeveridadeAtual = wflWorkflowEventosForSeveridadeAtual;
       this.wflWorkflowEventosForSeveridadeAnterior = wflWorkflowEventosForSeveridadeAnterior;
       this.supSolicitacaos = supSolicitacaos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_severidade", unique=true, nullable=false)
    public Integer getIdSeveridade() {
        return this.idSeveridade;
    }
    
    public void setIdSeveridade(Integer idSeveridade) {
        this.idSeveridade = idSeveridade;
    }

    
    @Column(name="cod_severidade", nullable=false, length=3)
    public String getCodSeveridade() {
        return this.codSeveridade;
    }
    
    public void setCodSeveridade(String codSeveridade) {
        this.codSeveridade = codSeveridade;
    }

    
    @Column(name="descricao_severidade", length=100)
    public String getDescricaoSeveridade() {
        return this.descricaoSeveridade;
    }
    
    public void setDescricaoSeveridade(String descricaoSeveridade) {
        this.descricaoSeveridade = descricaoSeveridade;
    }

    
    @Column(name="prioridade", unique=true, nullable=false)
    public int getPrioridade() {
        return this.prioridade;
    }
    
    public void setPrioridade(int prioridade) {
        this.prioridade = prioridade;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="wflSeveridade")
    public Set getWflWorkflows() {
        return this.wflWorkflows;
    }
    
    public void setWflWorkflows(Set wflWorkflows) {
        this.wflWorkflows = wflWorkflows;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="wflSeveridadeBySeveridadeAtual")
    public Set getWflWorkflowEventosForSeveridadeAtual() {
        return this.wflWorkflowEventosForSeveridadeAtual;
    }
    
    public void setWflWorkflowEventosForSeveridadeAtual(Set wflWorkflowEventosForSeveridadeAtual) {
        this.wflWorkflowEventosForSeveridadeAtual = wflWorkflowEventosForSeveridadeAtual;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="wflSeveridadeBySeveridadeAnterior")
    public Set getWflWorkflowEventosForSeveridadeAnterior() {
        return this.wflWorkflowEventosForSeveridadeAnterior;
    }
    
    public void setWflWorkflowEventosForSeveridadeAnterior(Set wflWorkflowEventosForSeveridadeAnterior) {
        this.wflWorkflowEventosForSeveridadeAnterior = wflWorkflowEventosForSeveridadeAnterior;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="wflSeveridade")
    public Set getSupSolicitacaos() {
        return this.supSolicitacaos;
    }
    
    public void setSupSolicitacaos(Set supSolicitacaos) {
        this.supSolicitacaos = supSolicitacaos;
    }




}


