package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WflWorkflow generated by hbm2java
 */
@Entity
@Table(name="wfl_workflow"
    ,catalog="jvmdsoftware"
)
public class WflWorkflow  implements java.io.Serializable {


     private Integer idWorkflow;
     private PubEmpresa pubEmpresaByEmpresaDestino;
     private PubEmpresa pubEmpresaByEmpresaCriacao;
     private PubFuncionalidade pubFuncionalidade;
     private PubSistema pubSistema;
     private PubUsuario pubUsuario;
     private WflSeveridade wflSeveridade;
     private WflSituacao wflSituacao;
     private Date dataHoraCriacao;
     private int idProcessoSistema;
     private Set comCompraOrdems = new HashSet(0);
     private Set servOrdemServicos = new HashSet(0);
     private Set wflWorkflowEventos = new HashSet(0);

    public WflWorkflow() {
    }

	
    public WflWorkflow(PubEmpresa pubEmpresaByEmpresaDestino, PubEmpresa pubEmpresaByEmpresaCriacao, PubFuncionalidade pubFuncionalidade, PubSistema pubSistema, PubUsuario pubUsuario, WflSeveridade wflSeveridade, WflSituacao wflSituacao, Date dataHoraCriacao, int idProcessoSistema) {
        this.pubEmpresaByEmpresaDestino = pubEmpresaByEmpresaDestino;
        this.pubEmpresaByEmpresaCriacao = pubEmpresaByEmpresaCriacao;
        this.pubFuncionalidade = pubFuncionalidade;
        this.pubSistema = pubSistema;
        this.pubUsuario = pubUsuario;
        this.wflSeveridade = wflSeveridade;
        this.wflSituacao = wflSituacao;
        this.dataHoraCriacao = dataHoraCriacao;
        this.idProcessoSistema = idProcessoSistema;
    }
    public WflWorkflow(PubEmpresa pubEmpresaByEmpresaDestino, PubEmpresa pubEmpresaByEmpresaCriacao, PubFuncionalidade pubFuncionalidade, PubSistema pubSistema, PubUsuario pubUsuario, WflSeveridade wflSeveridade, WflSituacao wflSituacao, Date dataHoraCriacao, int idProcessoSistema, Set comCompraOrdems, Set servOrdemServicos, Set wflWorkflowEventos) {
       this.pubEmpresaByEmpresaDestino = pubEmpresaByEmpresaDestino;
       this.pubEmpresaByEmpresaCriacao = pubEmpresaByEmpresaCriacao;
       this.pubFuncionalidade = pubFuncionalidade;
       this.pubSistema = pubSistema;
       this.pubUsuario = pubUsuario;
       this.wflSeveridade = wflSeveridade;
       this.wflSituacao = wflSituacao;
       this.dataHoraCriacao = dataHoraCriacao;
       this.idProcessoSistema = idProcessoSistema;
       this.comCompraOrdems = comCompraOrdems;
       this.servOrdemServicos = servOrdemServicos;
       this.wflWorkflowEventos = wflWorkflowEventos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_workflow", unique=true, nullable=false)
    public Integer getIdWorkflow() {
        return this.idWorkflow;
    }
    
    public void setIdWorkflow(Integer idWorkflow) {
        this.idWorkflow = idWorkflow;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa_destino", nullable=false)
    public PubEmpresa getPubEmpresaByEmpresaDestino() {
        return this.pubEmpresaByEmpresaDestino;
    }
    
    public void setPubEmpresaByEmpresaDestino(PubEmpresa pubEmpresaByEmpresaDestino) {
        this.pubEmpresaByEmpresaDestino = pubEmpresaByEmpresaDestino;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa_criacao", nullable=false)
    public PubEmpresa getPubEmpresaByEmpresaCriacao() {
        return this.pubEmpresaByEmpresaCriacao;
    }
    
    public void setPubEmpresaByEmpresaCriacao(PubEmpresa pubEmpresaByEmpresaCriacao) {
        this.pubEmpresaByEmpresaCriacao = pubEmpresaByEmpresaCriacao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionalidade", nullable=false)
    public PubFuncionalidade getPubFuncionalidade() {
        return this.pubFuncionalidade;
    }
    
    public void setPubFuncionalidade(PubFuncionalidade pubFuncionalidade) {
        this.pubFuncionalidade = pubFuncionalidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sistema", nullable=false)
    public PubSistema getPubSistema() {
        return this.pubSistema;
    }
    
    public void setPubSistema(PubSistema pubSistema) {
        this.pubSistema = pubSistema;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_criacao", nullable=false)
    public PubUsuario getPubUsuario() {
        return this.pubUsuario;
    }
    
    public void setPubUsuario(PubUsuario pubUsuario) {
        this.pubUsuario = pubUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="severidade", nullable=false)
    public WflSeveridade getWflSeveridade() {
        return this.wflSeveridade;
    }
    
    public void setWflSeveridade(WflSeveridade wflSeveridade) {
        this.wflSeveridade = wflSeveridade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="situacao", nullable=false)
    public WflSituacao getWflSituacao() {
        return this.wflSituacao;
    }
    
    public void setWflSituacao(WflSituacao wflSituacao) {
        this.wflSituacao = wflSituacao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_hora_criacao", nullable=false, length=19)
    public Date getDataHoraCriacao() {
        return this.dataHoraCriacao;
    }
    
    public void setDataHoraCriacao(Date dataHoraCriacao) {
        this.dataHoraCriacao = dataHoraCriacao;
    }

    
    @Column(name="id_processo_sistema", nullable=false)
    public int getIdProcessoSistema() {
        return this.idProcessoSistema;
    }
    
    public void setIdProcessoSistema(int idProcessoSistema) {
        this.idProcessoSistema = idProcessoSistema;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="wflWorkflow")
    public Set getComCompraOrdems() {
        return this.comCompraOrdems;
    }
    
    public void setComCompraOrdems(Set comCompraOrdems) {
        this.comCompraOrdems = comCompraOrdems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="wflWorkflow")
    public Set getServOrdemServicos() {
        return this.servOrdemServicos;
    }
    
    public void setServOrdemServicos(Set servOrdemServicos) {
        this.servOrdemServicos = servOrdemServicos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="wflWorkflow")
    public Set getWflWorkflowEventos() {
        return this.wflWorkflowEventos;
    }
    
    public void setWflWorkflowEventos(Set wflWorkflowEventos) {
        this.wflWorkflowEventos = wflWorkflowEventos;
    }




}


