package br.com.jvmsoftware.entities;
// Generated 31/Mar/2016 22:28:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WflWorkflow generated by hbm2java
 */
public class WflWorkflow  implements java.io.Serializable {


     private Integer idWorkflow;
     private PubEmpresa pubEmpresaByEmpresaDestino;
     private PubEmpresa pubEmpresaByEmpresaCriacao;
     private PubFuncionalidade pubFuncionalidade;
     private PubSistema pubSistema;
     private PubUsuario pubUsuario;
     private WflSeveridade wflSeveridade;
     private WflSituacao wflSituacao;
     private Date dataHoraCriacao;
     private int idProcessoSistema;
     private Set<WflWorkflowEvento> wflWorkflowEventos = new HashSet<WflWorkflowEvento>(0);

    public WflWorkflow() {
    }

	
    public WflWorkflow(PubEmpresa pubEmpresaByEmpresaDestino, PubEmpresa pubEmpresaByEmpresaCriacao, PubFuncionalidade pubFuncionalidade, PubSistema pubSistema, PubUsuario pubUsuario, WflSeveridade wflSeveridade, WflSituacao wflSituacao, Date dataHoraCriacao, int idProcessoSistema) {
        this.pubEmpresaByEmpresaDestino = pubEmpresaByEmpresaDestino;
        this.pubEmpresaByEmpresaCriacao = pubEmpresaByEmpresaCriacao;
        this.pubFuncionalidade = pubFuncionalidade;
        this.pubSistema = pubSistema;
        this.pubUsuario = pubUsuario;
        this.wflSeveridade = wflSeveridade;
        this.wflSituacao = wflSituacao;
        this.dataHoraCriacao = dataHoraCriacao;
        this.idProcessoSistema = idProcessoSistema;
    }
    public WflWorkflow(PubEmpresa pubEmpresaByEmpresaDestino, PubEmpresa pubEmpresaByEmpresaCriacao, PubFuncionalidade pubFuncionalidade, PubSistema pubSistema, PubUsuario pubUsuario, WflSeveridade wflSeveridade, WflSituacao wflSituacao, Date dataHoraCriacao, int idProcessoSistema, Set<WflWorkflowEvento> wflWorkflowEventos) {
       this.pubEmpresaByEmpresaDestino = pubEmpresaByEmpresaDestino;
       this.pubEmpresaByEmpresaCriacao = pubEmpresaByEmpresaCriacao;
       this.pubFuncionalidade = pubFuncionalidade;
       this.pubSistema = pubSistema;
       this.pubUsuario = pubUsuario;
       this.wflSeveridade = wflSeveridade;
       this.wflSituacao = wflSituacao;
       this.dataHoraCriacao = dataHoraCriacao;
       this.idProcessoSistema = idProcessoSistema;
       this.wflWorkflowEventos = wflWorkflowEventos;
    }
   
    public Integer getIdWorkflow() {
        return this.idWorkflow;
    }
    
    public void setIdWorkflow(Integer idWorkflow) {
        this.idWorkflow = idWorkflow;
    }
    public PubEmpresa getPubEmpresaByEmpresaDestino() {
        return this.pubEmpresaByEmpresaDestino;
    }
    
    public void setPubEmpresaByEmpresaDestino(PubEmpresa pubEmpresaByEmpresaDestino) {
        this.pubEmpresaByEmpresaDestino = pubEmpresaByEmpresaDestino;
    }
    public PubEmpresa getPubEmpresaByEmpresaCriacao() {
        return this.pubEmpresaByEmpresaCriacao;
    }
    
    public void setPubEmpresaByEmpresaCriacao(PubEmpresa pubEmpresaByEmpresaCriacao) {
        this.pubEmpresaByEmpresaCriacao = pubEmpresaByEmpresaCriacao;
    }
    public PubFuncionalidade getPubFuncionalidade() {
        return this.pubFuncionalidade;
    }
    
    public void setPubFuncionalidade(PubFuncionalidade pubFuncionalidade) {
        this.pubFuncionalidade = pubFuncionalidade;
    }
    public PubSistema getPubSistema() {
        return this.pubSistema;
    }
    
    public void setPubSistema(PubSistema pubSistema) {
        this.pubSistema = pubSistema;
    }
    public PubUsuario getPubUsuario() {
        return this.pubUsuario;
    }
    
    public void setPubUsuario(PubUsuario pubUsuario) {
        this.pubUsuario = pubUsuario;
    }
    public WflSeveridade getWflSeveridade() {
        return this.wflSeveridade;
    }
    
    public void setWflSeveridade(WflSeveridade wflSeveridade) {
        this.wflSeveridade = wflSeveridade;
    }
    public WflSituacao getWflSituacao() {
        return this.wflSituacao;
    }
    
    public void setWflSituacao(WflSituacao wflSituacao) {
        this.wflSituacao = wflSituacao;
    }
    public Date getDataHoraCriacao() {
        return this.dataHoraCriacao;
    }
    
    public void setDataHoraCriacao(Date dataHoraCriacao) {
        this.dataHoraCriacao = dataHoraCriacao;
    }
    public int getIdProcessoSistema() {
        return this.idProcessoSistema;
    }
    
    public void setIdProcessoSistema(int idProcessoSistema) {
        this.idProcessoSistema = idProcessoSistema;
    }
    public Set<WflWorkflowEvento> getWflWorkflowEventos() {
        return this.wflWorkflowEventos;
    }
    
    public void setWflWorkflowEventos(Set<WflWorkflowEvento> wflWorkflowEventos) {
        this.wflWorkflowEventos = wflWorkflowEventos;
    }




}


