package br.com.jvmsoftware.entities;
// Generated 31/Ago/2015 23:49:11 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WflWorkflowEvento generated by hbm2java
 */
public class WflWorkflowEvento  implements java.io.Serializable {


     private Integer idWorkflowEvento;
     private PubEmpresa pubEmpresa;
     private PubUsuario pubUsuario;
     private WflSeveridade wflSeveridadeBySeveridadeAtual;
     private WflSeveridade wflSeveridadeBySeveridadeAnterior;
     private WflSituacao wflSituacaoBySituacaoAnterior;
     private WflSituacao wflSituacaoBySituacaoAtual;
     private WflWorkflow wflWorkflow;
     private Date dataHoraEvento;

    public WflWorkflowEvento() {
    }

	
    public WflWorkflowEvento(PubEmpresa pubEmpresa, PubUsuario pubUsuario, WflSeveridade wflSeveridadeBySeveridadeAtual, WflSituacao wflSituacaoBySituacaoAtual, WflWorkflow wflWorkflow, Date dataHoraEvento) {
        this.pubEmpresa = pubEmpresa;
        this.pubUsuario = pubUsuario;
        this.wflSeveridadeBySeveridadeAtual = wflSeveridadeBySeveridadeAtual;
        this.wflSituacaoBySituacaoAtual = wflSituacaoBySituacaoAtual;
        this.wflWorkflow = wflWorkflow;
        this.dataHoraEvento = dataHoraEvento;
    }
    public WflWorkflowEvento(PubEmpresa pubEmpresa, PubUsuario pubUsuario, WflSeveridade wflSeveridadeBySeveridadeAtual, WflSeveridade wflSeveridadeBySeveridadeAnterior, WflSituacao wflSituacaoBySituacaoAnterior, WflSituacao wflSituacaoBySituacaoAtual, WflWorkflow wflWorkflow, Date dataHoraEvento) {
       this.pubEmpresa = pubEmpresa;
       this.pubUsuario = pubUsuario;
       this.wflSeveridadeBySeveridadeAtual = wflSeveridadeBySeveridadeAtual;
       this.wflSeveridadeBySeveridadeAnterior = wflSeveridadeBySeveridadeAnterior;
       this.wflSituacaoBySituacaoAnterior = wflSituacaoBySituacaoAnterior;
       this.wflSituacaoBySituacaoAtual = wflSituacaoBySituacaoAtual;
       this.wflWorkflow = wflWorkflow;
       this.dataHoraEvento = dataHoraEvento;
    }
   
    public Integer getIdWorkflowEvento() {
        return this.idWorkflowEvento;
    }
    
    public void setIdWorkflowEvento(Integer idWorkflowEvento) {
        this.idWorkflowEvento = idWorkflowEvento;
    }
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }
    public PubUsuario getPubUsuario() {
        return this.pubUsuario;
    }
    
    public void setPubUsuario(PubUsuario pubUsuario) {
        this.pubUsuario = pubUsuario;
    }
    public WflSeveridade getWflSeveridadeBySeveridadeAtual() {
        return this.wflSeveridadeBySeveridadeAtual;
    }
    
    public void setWflSeveridadeBySeveridadeAtual(WflSeveridade wflSeveridadeBySeveridadeAtual) {
        this.wflSeveridadeBySeveridadeAtual = wflSeveridadeBySeveridadeAtual;
    }
    public WflSeveridade getWflSeveridadeBySeveridadeAnterior() {
        return this.wflSeveridadeBySeveridadeAnterior;
    }
    
    public void setWflSeveridadeBySeveridadeAnterior(WflSeveridade wflSeveridadeBySeveridadeAnterior) {
        this.wflSeveridadeBySeveridadeAnterior = wflSeveridadeBySeveridadeAnterior;
    }
    public WflSituacao getWflSituacaoBySituacaoAnterior() {
        return this.wflSituacaoBySituacaoAnterior;
    }
    
    public void setWflSituacaoBySituacaoAnterior(WflSituacao wflSituacaoBySituacaoAnterior) {
        this.wflSituacaoBySituacaoAnterior = wflSituacaoBySituacaoAnterior;
    }
    public WflSituacao getWflSituacaoBySituacaoAtual() {
        return this.wflSituacaoBySituacaoAtual;
    }
    
    public void setWflSituacaoBySituacaoAtual(WflSituacao wflSituacaoBySituacaoAtual) {
        this.wflSituacaoBySituacaoAtual = wflSituacaoBySituacaoAtual;
    }
    public WflWorkflow getWflWorkflow() {
        return this.wflWorkflow;
    }
    
    public void setWflWorkflow(WflWorkflow wflWorkflow) {
        this.wflWorkflow = wflWorkflow;
    }
    public Date getDataHoraEvento() {
        return this.dataHoraEvento;
    }
    
    public void setDataHoraEvento(Date dataHoraEvento) {
        this.dataHoraEvento = dataHoraEvento;
    }




}


