package br.com.jvmsoftware.entities;
// Generated 12/Abr/2016 22:07:07 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WflWorkflowEvento generated by hbm2java
 */
@Entity
@Table(name="wfl_workflow_evento"
    ,catalog="jvmdsoftware"
)
public class WflWorkflowEvento  implements java.io.Serializable {


     private Integer idWorkflowEvento;
     private PubEmpresa pubEmpresa;
     private PubUsuario pubUsuario;
     private WflSeveridade wflSeveridadeBySeveridadeAtual;
     private WflSeveridade wflSeveridadeBySeveridadeAnterior;
     private WflSituacao wflSituacaoBySituacaoAnterior;
     private WflSituacao wflSituacaoBySituacaoAtual;
     private WflWorkflow wflWorkflow;
     private Date dataHoraEvento;

    public WflWorkflowEvento() {
    }

	
    public WflWorkflowEvento(PubEmpresa pubEmpresa, PubUsuario pubUsuario, WflSeveridade wflSeveridadeBySeveridadeAtual, WflSituacao wflSituacaoBySituacaoAtual, WflWorkflow wflWorkflow, Date dataHoraEvento) {
        this.pubEmpresa = pubEmpresa;
        this.pubUsuario = pubUsuario;
        this.wflSeveridadeBySeveridadeAtual = wflSeveridadeBySeveridadeAtual;
        this.wflSituacaoBySituacaoAtual = wflSituacaoBySituacaoAtual;
        this.wflWorkflow = wflWorkflow;
        this.dataHoraEvento = dataHoraEvento;
    }
    public WflWorkflowEvento(PubEmpresa pubEmpresa, PubUsuario pubUsuario, WflSeveridade wflSeveridadeBySeveridadeAtual, WflSeveridade wflSeveridadeBySeveridadeAnterior, WflSituacao wflSituacaoBySituacaoAnterior, WflSituacao wflSituacaoBySituacaoAtual, WflWorkflow wflWorkflow, Date dataHoraEvento) {
       this.pubEmpresa = pubEmpresa;
       this.pubUsuario = pubUsuario;
       this.wflSeveridadeBySeveridadeAtual = wflSeveridadeBySeveridadeAtual;
       this.wflSeveridadeBySeveridadeAnterior = wflSeveridadeBySeveridadeAnterior;
       this.wflSituacaoBySituacaoAnterior = wflSituacaoBySituacaoAnterior;
       this.wflSituacaoBySituacaoAtual = wflSituacaoBySituacaoAtual;
       this.wflWorkflow = wflWorkflow;
       this.dataHoraEvento = dataHoraEvento;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_workflow_evento", unique=true, nullable=false)
    public Integer getIdWorkflowEvento() {
        return this.idWorkflowEvento;
    }
    
    public void setIdWorkflowEvento(Integer idWorkflowEvento) {
        this.idWorkflowEvento = idWorkflowEvento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa_evento", nullable=false)
    public PubEmpresa getPubEmpresa() {
        return this.pubEmpresa;
    }
    
    public void setPubEmpresa(PubEmpresa pubEmpresa) {
        this.pubEmpresa = pubEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_evento", nullable=false)
    public PubUsuario getPubUsuario() {
        return this.pubUsuario;
    }
    
    public void setPubUsuario(PubUsuario pubUsuario) {
        this.pubUsuario = pubUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="severidade_atual", nullable=false)
    public WflSeveridade getWflSeveridadeBySeveridadeAtual() {
        return this.wflSeveridadeBySeveridadeAtual;
    }
    
    public void setWflSeveridadeBySeveridadeAtual(WflSeveridade wflSeveridadeBySeveridadeAtual) {
        this.wflSeveridadeBySeveridadeAtual = wflSeveridadeBySeveridadeAtual;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="severidade_anterior")
    public WflSeveridade getWflSeveridadeBySeveridadeAnterior() {
        return this.wflSeveridadeBySeveridadeAnterior;
    }
    
    public void setWflSeveridadeBySeveridadeAnterior(WflSeveridade wflSeveridadeBySeveridadeAnterior) {
        this.wflSeveridadeBySeveridadeAnterior = wflSeveridadeBySeveridadeAnterior;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="situacao_anterior")
    public WflSituacao getWflSituacaoBySituacaoAnterior() {
        return this.wflSituacaoBySituacaoAnterior;
    }
    
    public void setWflSituacaoBySituacaoAnterior(WflSituacao wflSituacaoBySituacaoAnterior) {
        this.wflSituacaoBySituacaoAnterior = wflSituacaoBySituacaoAnterior;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="situacao_atual", nullable=false)
    public WflSituacao getWflSituacaoBySituacaoAtual() {
        return this.wflSituacaoBySituacaoAtual;
    }
    
    public void setWflSituacaoBySituacaoAtual(WflSituacao wflSituacaoBySituacaoAtual) {
        this.wflSituacaoBySituacaoAtual = wflSituacaoBySituacaoAtual;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="workflow", nullable=false)
    public WflWorkflow getWflWorkflow() {
        return this.wflWorkflow;
    }
    
    public void setWflWorkflow(WflWorkflow wflWorkflow) {
        this.wflWorkflow = wflWorkflow;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_hora_evento", nullable=false, length=19)
    public Date getDataHoraEvento() {
        return this.dataHoraEvento;
    }
    
    public void setDataHoraEvento(Date dataHoraEvento) {
        this.dataHoraEvento = dataHoraEvento;
    }




}


